// Code generated by ent, DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// DispatchRef applies equality check predicate on the "dispatch_ref" field. It's identical to DispatchRefEQ.
func DispatchRef(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDispatchRef, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldState, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRetryCount, v))
}

// LoopIterationCount applies equality check predicate on the "loop_iteration_count" field. It's identical to LoopIterationCountEQ.
func LoopIterationCount(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldLoopIterationCount, v))
}

// Transport applies equality check predicate on the "transport" field. It's identical to TransportEQ.
func Transport(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTransport, v))
}

// Wave applies equality check predicate on the "wave" field. It's identical to WaveEQ.
func Wave(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldWave, v))
}

// TopoRank applies equality check predicate on the "topo_rank" field. It's identical to TopoRankEQ.
func TopoRank(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTopoRank, v))
}

// WorkspacePath applies equality check predicate on the "workspace_path" field. It's identical to WorkspacePathEQ.
func WorkspacePath(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldWorkspacePath, v))
}

// ArtifactPath applies equality check predicate on the "artifact_path" field. It's identical to ArtifactPathEQ.
func ArtifactPath(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldArtifactPath, v))
}

// LastErrorReason applies equality check predicate on the "last_error_reason" field. It's identical to LastErrorReasonEQ.
func LastErrorReason(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldLastErrorReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// TerminalAt applies equality check predicate on the "terminal_at" field. It's identical to TerminalAtEQ.
func TerminalAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTerminalAt, v))
}

// CardJSON applies equality check predicate on the "card_json" field. It's identical to CardJSONEQ.
func CardJSON(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCardJSON, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentID, v))
}

// RootID applies equality check predicate on the "root_id" field. It's identical to RootIDEQ.
func RootID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRootID, v))
}

// Depth applies equality check predicate on the "depth" field. It's identical to DepthEQ.
func Depth(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDepth, v))
}

// DecompositionStatus applies equality check predicate on the "decomposition_status" field. It's identical to DecompositionStatusEQ.
func DecompositionStatus(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDecompositionStatus, v))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldOrgID, v))
}

// AssignedAgentID applies equality check predicate on the "assigned_agent_id" field. It's identical to AssignedAgentIDEQ.
func AssignedAgentID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssignedAgentID, v))
}

// AssignedRoleID applies equality check predicate on the "assigned_role_id" field. It's identical to AssignedRoleIDEQ.
func AssignedRoleID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssignedRoleID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldProjectID, v))
}

// DispatchRefEQ applies the EQ predicate on the "dispatch_ref" field.
func DispatchRefEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDispatchRef, v))
}

// DispatchRefNEQ applies the NEQ predicate on the "dispatch_ref" field.
func DispatchRefNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDispatchRef, v))
}

// DispatchRefIn applies the In predicate on the "dispatch_ref" field.
func DispatchRefIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDispatchRef, vs...))
}

// DispatchRefNotIn applies the NotIn predicate on the "dispatch_ref" field.
func DispatchRefNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDispatchRef, vs...))
}

// DispatchRefGT applies the GT predicate on the "dispatch_ref" field.
func DispatchRefGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDispatchRef, v))
}

// DispatchRefGTE applies the GTE predicate on the "dispatch_ref" field.
func DispatchRefGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDispatchRef, v))
}

// DispatchRefLT applies the LT predicate on the "dispatch_ref" field.
func DispatchRefLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDispatchRef, v))
}

// DispatchRefLTE applies the LTE predicate on the "dispatch_ref" field.
func DispatchRefLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDispatchRef, v))
}

// DispatchRefContains applies the Contains predicate on the "dispatch_ref" field.
func DispatchRefContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldDispatchRef, v))
}

// DispatchRefHasPrefix applies the HasPrefix predicate on the "dispatch_ref" field.
func DispatchRefHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldDispatchRef, v))
}

// DispatchRefHasSuffix applies the HasSuffix predicate on the "dispatch_ref" field.
func DispatchRefHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldDispatchRef, v))
}

// DispatchRefEqualFold applies the EqualFold predicate on the "dispatch_ref" field.
func DispatchRefEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldDispatchRef, v))
}

// DispatchRefContainsFold applies the ContainsFold predicate on the "dispatch_ref" field.
func DispatchRefContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldDispatchRef, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldState, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldRetryCount, v))
}

// LoopIterationCountEQ applies the EQ predicate on the "loop_iteration_count" field.
func LoopIterationCountEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldLoopIterationCount, v))
}

// LoopIterationCountNEQ applies the NEQ predicate on the "loop_iteration_count" field.
func LoopIterationCountNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldLoopIterationCount, v))
}

// LoopIterationCountIn applies the In predicate on the "loop_iteration_count" field.
func LoopIterationCountIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldLoopIterationCount, vs...))
}

// LoopIterationCountNotIn applies the NotIn predicate on the "loop_iteration_count" field.
func LoopIterationCountNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldLoopIterationCount, vs...))
}

// LoopIterationCountGT applies the GT predicate on the "loop_iteration_count" field.
func LoopIterationCountGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldLoopIterationCount, v))
}

// LoopIterationCountGTE applies the GTE predicate on the "loop_iteration_count" field.
func LoopIterationCountGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldLoopIterationCount, v))
}

// LoopIterationCountLT applies the LT predicate on the "loop_iteration_count" field.
func LoopIterationCountLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldLoopIterationCount, v))
}

// LoopIterationCountLTE applies the LTE predicate on the "loop_iteration_count" field.
func LoopIterationCountLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldLoopIterationCount, v))
}

// TransportEQ applies the EQ predicate on the "transport" field.
func TransportEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTransport, v))
}

// TransportNEQ applies the NEQ predicate on the "transport" field.
func TransportNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTransport, v))
}

// TransportIn applies the In predicate on the "transport" field.
func TransportIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTransport, vs...))
}

// TransportNotIn applies the NotIn predicate on the "transport" field.
func TransportNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTransport, vs...))
}

// TransportGT applies the GT predicate on the "transport" field.
func TransportGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTransport, v))
}

// TransportGTE applies the GTE predicate on the "transport" field.
func TransportGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTransport, v))
}

// TransportLT applies the LT predicate on the "transport" field.
func TransportLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTransport, v))
}

// TransportLTE applies the LTE predicate on the "transport" field.
func TransportLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTransport, v))
}

// TransportContains applies the Contains predicate on the "transport" field.
func TransportContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTransport, v))
}

// TransportHasPrefix applies the HasPrefix predicate on the "transport" field.
func TransportHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTransport, v))
}

// TransportHasSuffix applies the HasSuffix predicate on the "transport" field.
func TransportHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTransport, v))
}

// TransportEqualFold applies the EqualFold predicate on the "transport" field.
func TransportEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTransport, v))
}

// TransportContainsFold applies the ContainsFold predicate on the "transport" field.
func TransportContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTransport, v))
}

// WaveEQ applies the EQ predicate on the "wave" field.
func WaveEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldWave, v))
}

// WaveNEQ applies the NEQ predicate on the "wave" field.
func WaveNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldWave, v))
}

// WaveIn applies the In predicate on the "wave" field.
func WaveIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldWave, vs...))
}

// WaveNotIn applies the NotIn predicate on the "wave" field.
func WaveNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldWave, vs...))
}

// WaveGT applies the GT predicate on the "wave" field.
func WaveGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldWave, v))
}

// WaveGTE applies the GTE predicate on the "wave" field.
func WaveGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldWave, v))
}

// WaveLT applies the LT predicate on the "wave" field.
func WaveLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldWave, v))
}

// WaveLTE applies the LTE predicate on the "wave" field.
func WaveLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldWave, v))
}

// TopoRankEQ applies the EQ predicate on the "topo_rank" field.
func TopoRankEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTopoRank, v))
}

// TopoRankNEQ applies the NEQ predicate on the "topo_rank" field.
func TopoRankNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTopoRank, v))
}

// TopoRankIn applies the In predicate on the "topo_rank" field.
func TopoRankIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTopoRank, vs...))
}

// TopoRankNotIn applies the NotIn predicate on the "topo_rank" field.
func TopoRankNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTopoRank, vs...))
}

// TopoRankGT applies the GT predicate on the "topo_rank" field.
func TopoRankGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTopoRank, v))
}

// TopoRankGTE applies the GTE predicate on the "topo_rank" field.
func TopoRankGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTopoRank, v))
}

// TopoRankLT applies the LT predicate on the "topo_rank" field.
func TopoRankLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTopoRank, v))
}

// TopoRankLTE applies the LTE predicate on the "topo_rank" field.
func TopoRankLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTopoRank, v))
}

// WorkspacePathEQ applies the EQ predicate on the "workspace_path" field.
func WorkspacePathEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldWorkspacePath, v))
}

// WorkspacePathNEQ applies the NEQ predicate on the "workspace_path" field.
func WorkspacePathNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldWorkspacePath, v))
}

// WorkspacePathIn applies the In predicate on the "workspace_path" field.
func WorkspacePathIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldWorkspacePath, vs...))
}

// WorkspacePathNotIn applies the NotIn predicate on the "workspace_path" field.
func WorkspacePathNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldWorkspacePath, vs...))
}

// WorkspacePathGT applies the GT predicate on the "workspace_path" field.
func WorkspacePathGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldWorkspacePath, v))
}

// WorkspacePathGTE applies the GTE predicate on the "workspace_path" field.
func WorkspacePathGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldWorkspacePath, v))
}

// WorkspacePathLT applies the LT predicate on the "workspace_path" field.
func WorkspacePathLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldWorkspacePath, v))
}

// WorkspacePathLTE applies the LTE predicate on the "workspace_path" field.
func WorkspacePathLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldWorkspacePath, v))
}

// WorkspacePathContains applies the Contains predicate on the "workspace_path" field.
func WorkspacePathContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldWorkspacePath, v))
}

// WorkspacePathHasPrefix applies the HasPrefix predicate on the "workspace_path" field.
func WorkspacePathHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldWorkspacePath, v))
}

// WorkspacePathHasSuffix applies the HasSuffix predicate on the "workspace_path" field.
func WorkspacePathHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldWorkspacePath, v))
}

// WorkspacePathIsNil applies the IsNil predicate on the "workspace_path" field.
func WorkspacePathIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldWorkspacePath))
}

// WorkspacePathNotNil applies the NotNil predicate on the "workspace_path" field.
func WorkspacePathNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldWorkspacePath))
}

// WorkspacePathEqualFold applies the EqualFold predicate on the "workspace_path" field.
func WorkspacePathEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldWorkspacePath, v))
}

// WorkspacePathContainsFold applies the ContainsFold predicate on the "workspace_path" field.
func WorkspacePathContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldWorkspacePath, v))
}

// ArtifactPathEQ applies the EQ predicate on the "artifact_path" field.
func ArtifactPathEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldArtifactPath, v))
}

// ArtifactPathNEQ applies the NEQ predicate on the "artifact_path" field.
func ArtifactPathNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldArtifactPath, v))
}

// ArtifactPathIn applies the In predicate on the "artifact_path" field.
func ArtifactPathIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldArtifactPath, vs...))
}

// ArtifactPathNotIn applies the NotIn predicate on the "artifact_path" field.
func ArtifactPathNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldArtifactPath, vs...))
}

// ArtifactPathGT applies the GT predicate on the "artifact_path" field.
func ArtifactPathGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldArtifactPath, v))
}

// ArtifactPathGTE applies the GTE predicate on the "artifact_path" field.
func ArtifactPathGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldArtifactPath, v))
}

// ArtifactPathLT applies the LT predicate on the "artifact_path" field.
func ArtifactPathLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldArtifactPath, v))
}

// ArtifactPathLTE applies the LTE predicate on the "artifact_path" field.
func ArtifactPathLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldArtifactPath, v))
}

// ArtifactPathContains applies the Contains predicate on the "artifact_path" field.
func ArtifactPathContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldArtifactPath, v))
}

// ArtifactPathHasPrefix applies the HasPrefix predicate on the "artifact_path" field.
func ArtifactPathHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldArtifactPath, v))
}

// ArtifactPathHasSuffix applies the HasSuffix predicate on the "artifact_path" field.
func ArtifactPathHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldArtifactPath, v))
}

// ArtifactPathIsNil applies the IsNil predicate on the "artifact_path" field.
func ArtifactPathIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldArtifactPath))
}

// ArtifactPathNotNil applies the NotNil predicate on the "artifact_path" field.
func ArtifactPathNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldArtifactPath))
}

// ArtifactPathEqualFold applies the EqualFold predicate on the "artifact_path" field.
func ArtifactPathEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldArtifactPath, v))
}

// ArtifactPathContainsFold applies the ContainsFold predicate on the "artifact_path" field.
func ArtifactPathContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldArtifactPath, v))
}

// LastErrorReasonEQ applies the EQ predicate on the "last_error_reason" field.
func LastErrorReasonEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldLastErrorReason, v))
}

// LastErrorReasonNEQ applies the NEQ predicate on the "last_error_reason" field.
func LastErrorReasonNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldLastErrorReason, v))
}

// LastErrorReasonIn applies the In predicate on the "last_error_reason" field.
func LastErrorReasonIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldLastErrorReason, vs...))
}

// LastErrorReasonNotIn applies the NotIn predicate on the "last_error_reason" field.
func LastErrorReasonNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldLastErrorReason, vs...))
}

// LastErrorReasonGT applies the GT predicate on the "last_error_reason" field.
func LastErrorReasonGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldLastErrorReason, v))
}

// LastErrorReasonGTE applies the GTE predicate on the "last_error_reason" field.
func LastErrorReasonGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldLastErrorReason, v))
}

// LastErrorReasonLT applies the LT predicate on the "last_error_reason" field.
func LastErrorReasonLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldLastErrorReason, v))
}

// LastErrorReasonLTE applies the LTE predicate on the "last_error_reason" field.
func LastErrorReasonLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldLastErrorReason, v))
}

// LastErrorReasonContains applies the Contains predicate on the "last_error_reason" field.
func LastErrorReasonContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldLastErrorReason, v))
}

// LastErrorReasonHasPrefix applies the HasPrefix predicate on the "last_error_reason" field.
func LastErrorReasonHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldLastErrorReason, v))
}

// LastErrorReasonHasSuffix applies the HasSuffix predicate on the "last_error_reason" field.
func LastErrorReasonHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldLastErrorReason, v))
}

// LastErrorReasonIsNil applies the IsNil predicate on the "last_error_reason" field.
func LastErrorReasonIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldLastErrorReason))
}

// LastErrorReasonNotNil applies the NotNil predicate on the "last_error_reason" field.
func LastErrorReasonNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldLastErrorReason))
}

// LastErrorReasonEqualFold applies the EqualFold predicate on the "last_error_reason" field.
func LastErrorReasonEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldLastErrorReason, v))
}

// LastErrorReasonContainsFold applies the ContainsFold predicate on the "last_error_reason" field.
func LastErrorReasonContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldLastErrorReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdatedAt, v))
}

// TerminalAtEQ applies the EQ predicate on the "terminal_at" field.
func TerminalAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTerminalAt, v))
}

// TerminalAtNEQ applies the NEQ predicate on the "terminal_at" field.
func TerminalAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTerminalAt, v))
}

// TerminalAtIn applies the In predicate on the "terminal_at" field.
func TerminalAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTerminalAt, vs...))
}

// TerminalAtNotIn applies the NotIn predicate on the "terminal_at" field.
func TerminalAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTerminalAt, vs...))
}

// TerminalAtGT applies the GT predicate on the "terminal_at" field.
func TerminalAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTerminalAt, v))
}

// TerminalAtGTE applies the GTE predicate on the "terminal_at" field.
func TerminalAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTerminalAt, v))
}

// TerminalAtLT applies the LT predicate on the "terminal_at" field.
func TerminalAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTerminalAt, v))
}

// TerminalAtLTE applies the LTE predicate on the "terminal_at" field.
func TerminalAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTerminalAt, v))
}

// TerminalAtIsNil applies the IsNil predicate on the "terminal_at" field.
func TerminalAtIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldTerminalAt))
}

// TerminalAtNotNil applies the NotNil predicate on the "terminal_at" field.
func TerminalAtNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldTerminalAt))
}

// CardJSONEQ applies the EQ predicate on the "card_json" field.
func CardJSONEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCardJSON, v))
}

// CardJSONNEQ applies the NEQ predicate on the "card_json" field.
func CardJSONNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCardJSON, v))
}

// CardJSONIn applies the In predicate on the "card_json" field.
func CardJSONIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCardJSON, vs...))
}

// CardJSONNotIn applies the NotIn predicate on the "card_json" field.
func CardJSONNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCardJSON, vs...))
}

// CardJSONGT applies the GT predicate on the "card_json" field.
func CardJSONGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCardJSON, v))
}

// CardJSONGTE applies the GTE predicate on the "card_json" field.
func CardJSONGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCardJSON, v))
}

// CardJSONLT applies the LT predicate on the "card_json" field.
func CardJSONLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCardJSON, v))
}

// CardJSONLTE applies the LTE predicate on the "card_json" field.
func CardJSONLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCardJSON, v))
}

// CardJSONContains applies the Contains predicate on the "card_json" field.
func CardJSONContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldCardJSON, v))
}

// CardJSONHasPrefix applies the HasPrefix predicate on the "card_json" field.
func CardJSONHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldCardJSON, v))
}

// CardJSONHasSuffix applies the HasSuffix predicate on the "card_json" field.
func CardJSONHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldCardJSON, v))
}

// CardJSONEqualFold applies the EqualFold predicate on the "card_json" field.
func CardJSONEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldCardJSON, v))
}

// CardJSONContainsFold applies the ContainsFold predicate on the "card_json" field.
func CardJSONContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldCardJSON, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldParentID))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldParentID, v))
}

// RootIDEQ applies the EQ predicate on the "root_id" field.
func RootIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRootID, v))
}

// RootIDNEQ applies the NEQ predicate on the "root_id" field.
func RootIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldRootID, v))
}

// RootIDIn applies the In predicate on the "root_id" field.
func RootIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldRootID, vs...))
}

// RootIDNotIn applies the NotIn predicate on the "root_id" field.
func RootIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldRootID, vs...))
}

// RootIDGT applies the GT predicate on the "root_id" field.
func RootIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldRootID, v))
}

// RootIDGTE applies the GTE predicate on the "root_id" field.
func RootIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldRootID, v))
}

// RootIDLT applies the LT predicate on the "root_id" field.
func RootIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldRootID, v))
}

// RootIDLTE applies the LTE predicate on the "root_id" field.
func RootIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldRootID, v))
}

// RootIDContains applies the Contains predicate on the "root_id" field.
func RootIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldRootID, v))
}

// RootIDHasPrefix applies the HasPrefix predicate on the "root_id" field.
func RootIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldRootID, v))
}

// RootIDHasSuffix applies the HasSuffix predicate on the "root_id" field.
func RootIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldRootID, v))
}

// RootIDIsNil applies the IsNil predicate on the "root_id" field.
func RootIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldRootID))
}

// RootIDNotNil applies the NotNil predicate on the "root_id" field.
func RootIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldRootID))
}

// RootIDEqualFold applies the EqualFold predicate on the "root_id" field.
func RootIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldRootID, v))
}

// RootIDContainsFold applies the ContainsFold predicate on the "root_id" field.
func RootIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldRootID, v))
}

// DepthEQ applies the EQ predicate on the "depth" field.
func DepthEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDepth, v))
}

// DepthNEQ applies the NEQ predicate on the "depth" field.
func DepthNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDepth, v))
}

// DepthIn applies the In predicate on the "depth" field.
func DepthIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDepth, vs...))
}

// DepthNotIn applies the NotIn predicate on the "depth" field.
func DepthNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDepth, vs...))
}

// DepthGT applies the GT predicate on the "depth" field.
func DepthGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDepth, v))
}

// DepthGTE applies the GTE predicate on the "depth" field.
func DepthGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDepth, v))
}

// DepthLT applies the LT predicate on the "depth" field.
func DepthLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDepth, v))
}

// DepthLTE applies the LTE predicate on the "depth" field.
func DepthLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDepth, v))
}

// DecompositionStatusEQ applies the EQ predicate on the "decomposition_status" field.
func DecompositionStatusEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDecompositionStatus, v))
}

// DecompositionStatusNEQ applies the NEQ predicate on the "decomposition_status" field.
func DecompositionStatusNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDecompositionStatus, v))
}

// DecompositionStatusIn applies the In predicate on the "decomposition_status" field.
func DecompositionStatusIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDecompositionStatus, vs...))
}

// DecompositionStatusNotIn applies the NotIn predicate on the "decomposition_status" field.
func DecompositionStatusNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDecompositionStatus, vs...))
}

// DecompositionStatusGT applies the GT predicate on the "decomposition_status" field.
func DecompositionStatusGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDecompositionStatus, v))
}

// DecompositionStatusGTE applies the GTE predicate on the "decomposition_status" field.
func DecompositionStatusGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDecompositionStatus, v))
}

// DecompositionStatusLT applies the LT predicate on the "decomposition_status" field.
func DecompositionStatusLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDecompositionStatus, v))
}

// DecompositionStatusLTE applies the LTE predicate on the "decomposition_status" field.
func DecompositionStatusLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDecompositionStatus, v))
}

// DecompositionStatusContains applies the Contains predicate on the "decomposition_status" field.
func DecompositionStatusContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldDecompositionStatus, v))
}

// DecompositionStatusHasPrefix applies the HasPrefix predicate on the "decomposition_status" field.
func DecompositionStatusHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldDecompositionStatus, v))
}

// DecompositionStatusHasSuffix applies the HasSuffix predicate on the "decomposition_status" field.
func DecompositionStatusHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldDecompositionStatus, v))
}

// DecompositionStatusEqualFold applies the EqualFold predicate on the "decomposition_status" field.
func DecompositionStatusEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldDecompositionStatus, v))
}

// DecompositionStatusContainsFold applies the ContainsFold predicate on the "decomposition_status" field.
func DecompositionStatusContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldDecompositionStatus, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDIsNil applies the IsNil predicate on the "org_id" field.
func OrgIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldOrgID))
}

// OrgIDNotNil applies the NotNil predicate on the "org_id" field.
func OrgIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldOrgID))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldOrgID, v))
}

// AssignedAgentIDEQ applies the EQ predicate on the "assigned_agent_id" field.
func AssignedAgentIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssignedAgentID, v))
}

// AssignedAgentIDNEQ applies the NEQ predicate on the "assigned_agent_id" field.
func AssignedAgentIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAssignedAgentID, v))
}

// AssignedAgentIDIn applies the In predicate on the "assigned_agent_id" field.
func AssignedAgentIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAssignedAgentID, vs...))
}

// AssignedAgentIDNotIn applies the NotIn predicate on the "assigned_agent_id" field.
func AssignedAgentIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAssignedAgentID, vs...))
}

// AssignedAgentIDGT applies the GT predicate on the "assigned_agent_id" field.
func AssignedAgentIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldAssignedAgentID, v))
}

// AssignedAgentIDGTE applies the GTE predicate on the "assigned_agent_id" field.
func AssignedAgentIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldAssignedAgentID, v))
}

// AssignedAgentIDLT applies the LT predicate on the "assigned_agent_id" field.
func AssignedAgentIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldAssignedAgentID, v))
}

// AssignedAgentIDLTE applies the LTE predicate on the "assigned_agent_id" field.
func AssignedAgentIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldAssignedAgentID, v))
}

// AssignedAgentIDContains applies the Contains predicate on the "assigned_agent_id" field.
func AssignedAgentIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldAssignedAgentID, v))
}

// AssignedAgentIDHasPrefix applies the HasPrefix predicate on the "assigned_agent_id" field.
func AssignedAgentIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldAssignedAgentID, v))
}

// AssignedAgentIDHasSuffix applies the HasSuffix predicate on the "assigned_agent_id" field.
func AssignedAgentIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldAssignedAgentID, v))
}

// AssignedAgentIDIsNil applies the IsNil predicate on the "assigned_agent_id" field.
func AssignedAgentIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAssignedAgentID))
}

// AssignedAgentIDNotNil applies the NotNil predicate on the "assigned_agent_id" field.
func AssignedAgentIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAssignedAgentID))
}

// AssignedAgentIDEqualFold applies the EqualFold predicate on the "assigned_agent_id" field.
func AssignedAgentIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldAssignedAgentID, v))
}

// AssignedAgentIDContainsFold applies the ContainsFold predicate on the "assigned_agent_id" field.
func AssignedAgentIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldAssignedAgentID, v))
}

// AssignedRoleIDEQ applies the EQ predicate on the "assigned_role_id" field.
func AssignedRoleIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssignedRoleID, v))
}

// AssignedRoleIDNEQ applies the NEQ predicate on the "assigned_role_id" field.
func AssignedRoleIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAssignedRoleID, v))
}

// AssignedRoleIDIn applies the In predicate on the "assigned_role_id" field.
func AssignedRoleIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAssignedRoleID, vs...))
}

// AssignedRoleIDNotIn applies the NotIn predicate on the "assigned_role_id" field.
func AssignedRoleIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAssignedRoleID, vs...))
}

// AssignedRoleIDGT applies the GT predicate on the "assigned_role_id" field.
func AssignedRoleIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldAssignedRoleID, v))
}

// AssignedRoleIDGTE applies the GTE predicate on the "assigned_role_id" field.
func AssignedRoleIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldAssignedRoleID, v))
}

// AssignedRoleIDLT applies the LT predicate on the "assigned_role_id" field.
func AssignedRoleIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldAssignedRoleID, v))
}

// AssignedRoleIDLTE applies the LTE predicate on the "assigned_role_id" field.
func AssignedRoleIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldAssignedRoleID, v))
}

// AssignedRoleIDContains applies the Contains predicate on the "assigned_role_id" field.
func AssignedRoleIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldAssignedRoleID, v))
}

// AssignedRoleIDHasPrefix applies the HasPrefix predicate on the "assigned_role_id" field.
func AssignedRoleIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldAssignedRoleID, v))
}

// AssignedRoleIDHasSuffix applies the HasSuffix predicate on the "assigned_role_id" field.
func AssignedRoleIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldAssignedRoleID, v))
}

// AssignedRoleIDIsNil applies the IsNil predicate on the "assigned_role_id" field.
func AssignedRoleIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAssignedRoleID))
}

// AssignedRoleIDNotNil applies the NotNil predicate on the "assigned_role_id" field.
func AssignedRoleIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAssignedRoleID))
}

// AssignedRoleIDEqualFold applies the EqualFold predicate on the "assigned_role_id" field.
func AssignedRoleIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldAssignedRoleID, v))
}

// AssignedRoleIDContainsFold applies the ContainsFold predicate on the "assigned_role_id" field.
func AssignedRoleIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldAssignedRoleID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
