// Code generated by ent, DO NOT EDIT.

package wave

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the wave type in the database.
	Label = "wave"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldDispatchRef holds the string denoting the dispatch_ref field in the database.
	FieldDispatchRef = "dispatch_ref"
	// FieldWave holds the string denoting the wave field in the database.
	FieldWave = "wave"
	// FieldSealedAt holds the string denoting the sealed_at field in the database.
	FieldSealedAt = "sealed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the wave in the database.
	Table = "waves"
)

// Columns holds all SQL columns for wave fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldDispatchRef,
	FieldWave,
	FieldSealedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProjectID holds the default value on creation for the "project_id" field.
	DefaultProjectID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Wave queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByDispatchRef orders the results by the dispatch_ref field.
func ByDispatchRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchRef, opts...).ToFunc()
}

// ByWave orders the results by the wave field.
func ByWave(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWave, opts...).ToFunc()
}

// BySealedAt orders the results by the sealed_at field.
func BySealedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSealedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
