// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "project_id", Type: field.TypeString, Size: 2147483647, Default: "default"},
		{Name: "task_id", Type: field.TypeString, Size: 2147483647},
		{Name: "event_type", Type: field.TypeString, Size: 2147483647},
		{Name: "from_state", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "to_state", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "attempt", Type: field.TypeInt, Default: 0},
		{Name: "transport", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "runner_id", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "details", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_project_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2]},
			},
			{
				Name:    "event_task_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[3]},
			},
			{
				Name:    "event_timestamp",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[7]},
			},
			{
				Name:    "event_project_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2], EventsColumns[7]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "project_id", Type: field.TypeString, Size: 2147483647, Default: "default"},
		{Name: "dispatch_ref", Type: field.TypeString, Size: 2147483647},
		{Name: "state", Type: field.TypeString, Size: 2147483647, Default: "pending"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "loop_iteration_count", Type: field.TypeInt, Default: 0},
		{Name: "transport", Type: field.TypeString, Size: 2147483647},
		{Name: "wave", Type: field.TypeInt},
		{Name: "topo_rank", Type: field.TypeInt, Default: 0},
		{Name: "workspace_path", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "artifact_path", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "last_error_reason", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "terminal_at", Type: field.TypeTime, Nullable: true},
		{Name: "card_json", Type: field.TypeString, Size: 2147483647},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_project_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[1]},
			},
			{
				Name:    "task_dispatch_ref",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[2]},
			},
			{
				Name:    "task_state",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3]},
			},
			{
				Name:    "task_wave",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[7]},
			},
			{
				Name:    "task_project_id_state",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[1], TasksColumns[3]},
			},
		},
	}
	// WavesColumns holds the columns for the "waves" table.
	WavesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "project_id", Type: field.TypeString, Size: 2147483647, Default: "default"},
		{Name: "dispatch_ref", Type: field.TypeString, Size: 2147483647},
		{Name: "wave", Type: field.TypeInt},
		{Name: "sealed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WavesTable holds the schema information for the "waves" table.
	WavesTable = &schema.Table{
		Name:       "waves",
		Columns:    WavesColumns,
		PrimaryKey: []*schema.Column{WavesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wave_project_id",
				Unique:  false,
				Columns: []*schema.Column{WavesColumns[1]},
			},
			{
				Name:    "wave_project_id_dispatch_ref_wave",
				Unique:  true,
				Columns: []*schema.Column{WavesColumns[1], WavesColumns[2], WavesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		TasksTable,
		WavesTable,
	}
)

func init() {
}
