// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/agentcall"
)

// AgentCallCreate is the builder for creating a AgentCall entity.
type AgentCallCreate struct {
	config
	mutation *AgentCallMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *AgentCallCreate) SetTaskID(v string) *AgentCallCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *AgentCallCreate) SetAgentID(v string) *AgentCallCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetRunnerType sets the "runner_type" field.
func (_c *AgentCallCreate) SetRunnerType(v string) *AgentCallCreate {
	_c.mutation.SetRunnerType(v)
	return _c
}

// SetTaskType sets the "task_type" field.
func (_c *AgentCallCreate) SetTaskType(v string) *AgentCallCreate {
	_c.mutation.SetTaskType(v)
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *AgentCallCreate) SetTraceID(v string) *AgentCallCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableTraceID(v *string) *AgentCallCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentCallCreate) SetStatus(v string) *AgentCallCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *AgentCallCreate) SetExitCode(v int) *AgentCallCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableExitCode(v *int) *AgentCallCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AgentCallCreate) SetErrorMessage(v string) *AgentCallCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableErrorMessage(v *string) *AgentCallCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetOutputSummary sets the "output_summary" field.
func (_c *AgentCallCreate) SetOutputSummary(v string) *AgentCallCreate {
	_c.mutation.SetOutputSummary(v)
	return _c
}

// SetNillableOutputSummary sets the "output_summary" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableOutputSummary(v *string) *AgentCallCreate {
	if v != nil {
		_c.SetOutputSummary(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AgentCallCreate) SetDurationMs(v int64) *AgentCallCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableDurationMs(v *int64) *AgentCallCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AgentCallCreate) SetStartedAt(v time.Time) *AgentCallCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *AgentCallCreate) SetFinishedAt(v time.Time) *AgentCallCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCallCreate) SetCreatedAt(v time.Time) *AgentCallCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCallCreate) SetNillableCreatedAt(v *time.Time) *AgentCallCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCallCreate) SetID(v string) *AgentCallCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AgentCallMutation object of the builder.
func (_c *AgentCallCreate) Mutation() *AgentCallMutation {
	return _c.mutation
}

// Save creates the AgentCall in the database.
func (_c *AgentCallCreate) Save(ctx context.Context) (*AgentCall, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCallCreate) SaveX(ctx context.Context) *AgentCall {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCallCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCallCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCallCreate) defaults() {
	if _, ok := _c.mutation.ExitCode(); !ok {
		v := agentcall.DefaultExitCode
		_c.mutation.SetExitCode(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := agentcall.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentcall.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCallCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "AgentCall.task_id"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "AgentCall.agent_id"`)}
	}
	if _, ok := _c.mutation.RunnerType(); !ok {
		return &ValidationError{Name: "runner_type", err: errors.New(`ent: missing required field "AgentCall.runner_type"`)}
	}
	if _, ok := _c.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "AgentCall.task_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentCall.status"`)}
	}
	if _, ok := _c.mutation.ExitCode(); !ok {
		return &ValidationError{Name: "exit_code", err: errors.New(`ent: missing required field "AgentCall.exit_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "AgentCall.duration_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "AgentCall.started_at"`)}
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		return &ValidationError{Name: "finished_at", err: errors.New(`ent: missing required field "AgentCall.finished_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentCall.created_at"`)}
	}
	return nil
}

func (_c *AgentCallCreate) sqlSave(ctx context.Context) (*AgentCall, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentCall.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCallCreate) createSpec() (*AgentCall, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentCall{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentcall.Table, sqlgraph.NewFieldSpec(agentcall.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(agentcall.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(agentcall.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.RunnerType(); ok {
		_spec.SetField(agentcall.FieldRunnerType, field.TypeString, value)
		_node.RunnerType = value
	}
	if value, ok := _c.mutation.TaskType(); ok {
		_spec.SetField(agentcall.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(agentcall.FieldTraceID, field.TypeString, value)
		_node.TraceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentcall.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(agentcall.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(agentcall.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.OutputSummary(); ok {
		_spec.SetField(agentcall.FieldOutputSummary, field.TypeString, value)
		_node.OutputSummary = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(agentcall.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(agentcall.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(agentcall.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentcall.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AgentCallCreateBulk is the builder for creating many AgentCall entities in bulk.
type AgentCallCreateBulk struct {
	config
	err      error
	builders []*AgentCallCreate
}

// Save creates the AgentCall entities in the database.
func (_c *AgentCallCreateBulk) Save(ctx context.Context) ([]*AgentCall, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentCall, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentCallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCallCreateBulk) SaveX(ctx context.Context) []*AgentCall {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCallCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCallCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
