// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/apitoken"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// APITokenUpdate is the builder for updating APIToken entities.
type APITokenUpdate struct {
	config
	hooks    []Hook
	mutation *APITokenMutation
}

// Where appends a list predicates to the APITokenUpdate builder.
func (_u *APITokenUpdate) Where(ps ...predicate.APIToken) *APITokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *APITokenUpdate) SetToken(v string) *APITokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableToken(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APITokenUpdate) SetName(v string) *APITokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableName(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APITokenUpdate) SetDescription(v string) *APITokenUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableDescription(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *APITokenUpdate) ClearDescription() *APITokenUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *APITokenUpdate) SetUserID(v string) *APITokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableUserID(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *APITokenUpdate) SetScopes(v []string) *APITokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *APITokenUpdate) AppendScopes(v []string) *APITokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *APITokenUpdate) ClearScopes() *APITokenUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *APITokenUpdate) SetExpiresAt(v time.Time) *APITokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableExpiresAt(v *time.Time) *APITokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *APITokenUpdate) ClearExpiresAt() *APITokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APITokenUpdate) SetLastUsedAt(v time.Time) *APITokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableLastUsedAt(v *time.Time) *APITokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APITokenUpdate) ClearLastUsedAt() *APITokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *APITokenUpdate) SetRevoked(v bool) *APITokenUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableRevoked(v *bool) *APITokenUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *APITokenUpdate) SetRevokedAt(v time.Time) *APITokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableRevokedAt(v *time.Time) *APITokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *APITokenUpdate) ClearRevokedAt() *APITokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *APITokenUpdate) SetRevokedReason(v string) *APITokenUpdate {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableRevokedReason(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *APITokenUpdate) ClearRevokedReason() *APITokenUpdate {
	_u.mutation.ClearRevokedReason()
	return _u
}

// Mutation returns the APITokenMutation object of the builder.
func (_u *APITokenUpdate) Mutation() *APITokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APITokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APITokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APITokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APITokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APITokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(apitoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apitoken.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apitoken.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apitoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apitoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apitoken.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(apitoken.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(apitoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apitoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apitoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(apitoken.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(apitoken.FieldRevokedReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APITokenUpdateOne is the builder for updating a single APIToken entity.
type APITokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APITokenMutation
}

// SetToken sets the "token" field.
func (_u *APITokenUpdateOne) SetToken(v string) *APITokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableToken(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APITokenUpdateOne) SetName(v string) *APITokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableName(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APITokenUpdateOne) SetDescription(v string) *APITokenUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableDescription(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *APITokenUpdateOne) ClearDescription() *APITokenUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *APITokenUpdateOne) SetUserID(v string) *APITokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableUserID(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *APITokenUpdateOne) SetScopes(v []string) *APITokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *APITokenUpdateOne) AppendScopes(v []string) *APITokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *APITokenUpdateOne) ClearScopes() *APITokenUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *APITokenUpdateOne) SetExpiresAt(v time.Time) *APITokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableExpiresAt(v *time.Time) *APITokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *APITokenUpdateOne) ClearExpiresAt() *APITokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APITokenUpdateOne) SetLastUsedAt(v time.Time) *APITokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *APITokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APITokenUpdateOne) ClearLastUsedAt() *APITokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *APITokenUpdateOne) SetRevoked(v bool) *APITokenUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableRevoked(v *bool) *APITokenUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *APITokenUpdateOne) SetRevokedAt(v time.Time) *APITokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableRevokedAt(v *time.Time) *APITokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *APITokenUpdateOne) ClearRevokedAt() *APITokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *APITokenUpdateOne) SetRevokedReason(v string) *APITokenUpdateOne {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableRevokedReason(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *APITokenUpdateOne) ClearRevokedReason() *APITokenUpdateOne {
	_u.mutation.ClearRevokedReason()
	return _u
}

// Mutation returns the APITokenMutation object of the builder.
func (_u *APITokenUpdateOne) Mutation() *APITokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the APITokenUpdate builder.
func (_u *APITokenUpdateOne) Where(ps ...predicate.APIToken) *APITokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APITokenUpdateOne) Select(field string, fields ...string) *APITokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIToken entity.
func (_u *APITokenUpdateOne) Save(ctx context.Context) (*APIToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APITokenUpdateOne) SaveX(ctx context.Context) *APIToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APITokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APITokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APITokenUpdateOne) sqlSave(ctx context.Context) (_node *APIToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apitoken.FieldID)
		for _, f := range fields {
			if !apitoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(apitoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apitoken.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apitoken.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apitoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apitoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apitoken.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(apitoken.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(apitoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apitoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apitoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(apitoken.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(apitoken.FieldRevokedReason, field.TypeString)
	}
	_node = &APIToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
