// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/event"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *EventCreate) SetEventID(v string) *EventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *EventCreate) SetProjectID(v string) *EventCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableProjectID(v *string) *EventCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *EventCreate) SetTaskID(v string) *EventCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *EventCreate) SetEventType(v string) *EventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetFromState sets the "from_state" field.
func (_c *EventCreate) SetFromState(v string) *EventCreate {
	_c.mutation.SetFromState(v)
	return _c
}

// SetNillableFromState sets the "from_state" field if the given value is not nil.
func (_c *EventCreate) SetNillableFromState(v *string) *EventCreate {
	if v != nil {
		_c.SetFromState(*v)
	}
	return _c
}

// SetToState sets the "to_state" field.
func (_c *EventCreate) SetToState(v string) *EventCreate {
	_c.mutation.SetToState(v)
	return _c
}

// SetNillableToState sets the "to_state" field if the given value is not nil.
func (_c *EventCreate) SetNillableToState(v *string) *EventCreate {
	if v != nil {
		_c.SetToState(*v)
	}
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *EventCreate) SetTimestamp(v time.Time) *EventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *EventCreate) SetNillableTimestamp(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *EventCreate) SetReason(v string) *EventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *EventCreate) SetNillableReason(v *string) *EventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *EventCreate) SetAttempt(v int) *EventCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *EventCreate) SetNillableAttempt(v *int) *EventCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *EventCreate) SetTransport(v string) *EventCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_c *EventCreate) SetNillableTransport(v *string) *EventCreate {
	if v != nil {
		_c.SetTransport(*v)
	}
	return _c
}

// SetRunnerID sets the "runner_id" field.
func (_c *EventCreate) SetRunnerID(v string) *EventCreate {
	_c.mutation.SetRunnerID(v)
	return _c
}

// SetNillableRunnerID sets the "runner_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableRunnerID(v *string) *EventCreate {
	if v != nil {
		_c.SetRunnerID(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *EventCreate) SetDetails(v string) *EventCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_c *EventCreate) SetNillableDetails(v *string) *EventCreate {
	if v != nil {
		_c.SetDetails(*v)
	}
	return _c
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := event.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := event.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		v := event.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Event.event_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Event.project_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Event.task_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "Event.event_type"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "Event.timestamp"`)}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "Event.attempt"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(event.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(event.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.FromState(); ok {
		_spec.SetField(event.FieldFromState, field.TypeString, value)
		_node.FromState = value
	}
	if value, ok := _c.mutation.ToState(); ok {
		_spec.SetField(event.FieldToState, field.TypeString, value)
		_node.ToState = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(event.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(event.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(event.FieldTransport, field.TypeString, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.RunnerID(); ok {
		_spec.SetField(event.FieldRunnerID, field.TypeString, value)
		_node.RunnerID = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(event.FieldDetails, field.TypeString, value)
		_node.Details = value
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
