// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/knowledgespace"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// KnowledgeSpaceUpdate is the builder for updating KnowledgeSpace entities.
type KnowledgeSpaceUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeSpaceMutation
}

// Where appends a list predicates to the KnowledgeSpaceUpdate builder.
func (_u *KnowledgeSpaceUpdate) Where(ps ...predicate.KnowledgeSpace) *KnowledgeSpaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *KnowledgeSpaceUpdate) SetOrgID(v string) *KnowledgeSpaceUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdate) SetNillableOrgID(v *string) *KnowledgeSpaceUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *KnowledgeSpaceUpdate) SetProjectID(v string) *KnowledgeSpaceUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdate) SetNillableProjectID(v *string) *KnowledgeSpaceUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeSpaceUpdate) SetName(v string) *KnowledgeSpaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdate) SetNillableName(v *string) *KnowledgeSpaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeSpaceUpdate) SetDescription(v string) *KnowledgeSpaceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdate) SetNillableDescription(v *string) *KnowledgeSpaceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeSpaceUpdate) ClearDescription() *KnowledgeSpaceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *KnowledgeSpaceUpdate) SetCreatedAt(v time.Time) *KnowledgeSpaceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdate) SetNillableCreatedAt(v *time.Time) *KnowledgeSpaceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the KnowledgeSpaceMutation object of the builder.
func (_u *KnowledgeSpaceUpdate) Mutation() *KnowledgeSpaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeSpaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeSpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeSpaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeSpaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KnowledgeSpaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(knowledgespace.Table, knowledgespace.Columns, sqlgraph.NewFieldSpec(knowledgespace.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(knowledgespace.FieldOrgID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(knowledgespace.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgespace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgespace.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgespace.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgespace.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeSpaceUpdateOne is the builder for updating a single KnowledgeSpace entity.
type KnowledgeSpaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeSpaceMutation
}

// SetOrgID sets the "org_id" field.
func (_u *KnowledgeSpaceUpdateOne) SetOrgID(v string) *KnowledgeSpaceUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdateOne) SetNillableOrgID(v *string) *KnowledgeSpaceUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *KnowledgeSpaceUpdateOne) SetProjectID(v string) *KnowledgeSpaceUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdateOne) SetNillableProjectID(v *string) *KnowledgeSpaceUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeSpaceUpdateOne) SetName(v string) *KnowledgeSpaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdateOne) SetNillableName(v *string) *KnowledgeSpaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeSpaceUpdateOne) SetDescription(v string) *KnowledgeSpaceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdateOne) SetNillableDescription(v *string) *KnowledgeSpaceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeSpaceUpdateOne) ClearDescription() *KnowledgeSpaceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *KnowledgeSpaceUpdateOne) SetCreatedAt(v time.Time) *KnowledgeSpaceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *KnowledgeSpaceUpdateOne) SetNillableCreatedAt(v *time.Time) *KnowledgeSpaceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the KnowledgeSpaceMutation object of the builder.
func (_u *KnowledgeSpaceUpdateOne) Mutation() *KnowledgeSpaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the KnowledgeSpaceUpdate builder.
func (_u *KnowledgeSpaceUpdateOne) Where(ps ...predicate.KnowledgeSpace) *KnowledgeSpaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeSpaceUpdateOne) Select(field string, fields ...string) *KnowledgeSpaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeSpace entity.
func (_u *KnowledgeSpaceUpdateOne) Save(ctx context.Context) (*KnowledgeSpace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeSpaceUpdateOne) SaveX(ctx context.Context) *KnowledgeSpace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeSpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeSpaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KnowledgeSpaceUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeSpace, err error) {
	_spec := sqlgraph.NewUpdateSpec(knowledgespace.Table, knowledgespace.Columns, sqlgraph.NewFieldSpec(knowledgespace.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeSpace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgespace.FieldID)
		for _, f := range fields {
			if !knowledgespace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgespace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(knowledgespace.FieldOrgID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(knowledgespace.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgespace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgespace.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgespace.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgespace.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &KnowledgeSpace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
