// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/knowledgespace"
)

// KnowledgeSpaceCreate is the builder for creating a KnowledgeSpace entity.
type KnowledgeSpaceCreate struct {
	config
	mutation *KnowledgeSpaceMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *KnowledgeSpaceCreate) SetOrgID(v string) *KnowledgeSpaceCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *KnowledgeSpaceCreate) SetProjectID(v string) *KnowledgeSpaceCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *KnowledgeSpaceCreate) SetNillableProjectID(v *string) *KnowledgeSpaceCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *KnowledgeSpaceCreate) SetName(v string) *KnowledgeSpaceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *KnowledgeSpaceCreate) SetDescription(v string) *KnowledgeSpaceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *KnowledgeSpaceCreate) SetNillableDescription(v *string) *KnowledgeSpaceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KnowledgeSpaceCreate) SetCreatedAt(v time.Time) *KnowledgeSpaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KnowledgeSpaceCreate) SetNillableCreatedAt(v *time.Time) *KnowledgeSpaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KnowledgeSpaceCreate) SetID(v string) *KnowledgeSpaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the KnowledgeSpaceMutation object of the builder.
func (_c *KnowledgeSpaceCreate) Mutation() *KnowledgeSpaceMutation {
	return _c.mutation
}

// Save creates the KnowledgeSpace in the database.
func (_c *KnowledgeSpaceCreate) Save(ctx context.Context) (*KnowledgeSpace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeSpaceCreate) SaveX(ctx context.Context) *KnowledgeSpace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeSpaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeSpaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeSpaceCreate) defaults() {
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := knowledgespace.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := knowledgespace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeSpaceCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "KnowledgeSpace.org_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "KnowledgeSpace.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "KnowledgeSpace.name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KnowledgeSpace.created_at"`)}
	}
	return nil
}

func (_c *KnowledgeSpaceCreate) sqlSave(ctx context.Context) (*KnowledgeSpace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected KnowledgeSpace.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeSpaceCreate) createSpec() (*KnowledgeSpace, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeSpace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledgespace.Table, sqlgraph.NewFieldSpec(knowledgespace.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(knowledgespace.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(knowledgespace.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(knowledgespace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(knowledgespace.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgespace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// KnowledgeSpaceCreateBulk is the builder for creating many KnowledgeSpace entities in bulk.
type KnowledgeSpaceCreateBulk struct {
	config
	err      error
	builders []*KnowledgeSpaceCreate
}

// Save creates the KnowledgeSpace entities in the database.
func (_c *KnowledgeSpaceCreateBulk) Save(ctx context.Context) ([]*KnowledgeSpace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KnowledgeSpace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeSpaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeSpaceCreateBulk) SaveX(ctx context.Context) []*KnowledgeSpace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeSpaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeSpaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
