// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/message"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *MessageUpdate) SetSpaceID(v string) *MessageUpdate {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSpaceID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// SetFromAgentID sets the "from_agent_id" field.
func (_u *MessageUpdate) SetFromAgentID(v string) *MessageUpdate {
	_u.mutation.SetFromAgentID(v)
	return _u
}

// SetNillableFromAgentID sets the "from_agent_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableFromAgentID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetFromAgentID(*v)
	}
	return _u
}

// SetToAgentID sets the "to_agent_id" field.
func (_u *MessageUpdate) SetToAgentID(v string) *MessageUpdate {
	_u.mutation.SetToAgentID(v)
	return _u
}

// SetNillableToAgentID sets the "to_agent_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableToAgentID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetToAgentID(*v)
	}
	return _u
}

// ClearToAgentID clears the value of the "to_agent_id" field.
func (_u *MessageUpdate) ClearToAgentID() *MessageUpdate {
	_u.mutation.ClearToAgentID()
	return _u
}

// SetType sets the "type" field.
func (_u *MessageUpdate) SetType(v string) *MessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableType(v *string) *MessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *MessageUpdate) SetReadAt(v time.Time) *MessageUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableReadAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *MessageUpdate) ClearReadAt() *MessageUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MessageUpdate) SetCreatedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCreatedAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(message.FieldSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAgentID(); ok {
		_spec.SetField(message.FieldFromAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAgentID(); ok {
		_spec.SetField(message.FieldToAgentID, field.TypeString, value)
	}
	if _u.mutation.ToAgentIDCleared() {
		_spec.ClearField(message.FieldToAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(message.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(message.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetSpaceID sets the "space_id" field.
func (_u *MessageUpdateOne) SetSpaceID(v string) *MessageUpdateOne {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSpaceID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// SetFromAgentID sets the "from_agent_id" field.
func (_u *MessageUpdateOne) SetFromAgentID(v string) *MessageUpdateOne {
	_u.mutation.SetFromAgentID(v)
	return _u
}

// SetNillableFromAgentID sets the "from_agent_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableFromAgentID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetFromAgentID(*v)
	}
	return _u
}

// SetToAgentID sets the "to_agent_id" field.
func (_u *MessageUpdateOne) SetToAgentID(v string) *MessageUpdateOne {
	_u.mutation.SetToAgentID(v)
	return _u
}

// SetNillableToAgentID sets the "to_agent_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableToAgentID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetToAgentID(*v)
	}
	return _u
}

// ClearToAgentID clears the value of the "to_agent_id" field.
func (_u *MessageUpdateOne) ClearToAgentID() *MessageUpdateOne {
	_u.mutation.ClearToAgentID()
	return _u
}

// SetType sets the "type" field.
func (_u *MessageUpdateOne) SetType(v string) *MessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableType(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *MessageUpdateOne) SetReadAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableReadAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *MessageUpdateOne) ClearReadAt() *MessageUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MessageUpdateOne) SetCreatedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCreatedAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(message.FieldSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAgentID(); ok {
		_spec.SetField(message.FieldFromAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAgentID(); ok {
		_spec.SetField(message.FieldToAgentID, field.TypeString, value)
	}
	if _u.mutation.ToAgentIDCleared() {
		_spec.ClearField(message.FieldToAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(message.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(message.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
