// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mCP-DevOS/ai-orchestration-platform/ent/agent"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/agentcall"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/apitoken"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/contextentry"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/department"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/document"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/event"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/knowledgespace"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/message"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/organization"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/permission"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/role"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/schema"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/task"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/tasktemplate"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/team"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/user"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/wave"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apitokenFields := schema.APIToken{}.Fields()
	_ = apitokenFields
	// apitokenDescCreatedAt is the schema descriptor for created_at field.
	apitokenDescCreatedAt := apitokenFields[6].Descriptor()
	// apitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	apitoken.DefaultCreatedAt = apitokenDescCreatedAt.Default.(func() time.Time)
	// apitokenDescRevoked is the schema descriptor for revoked field.
	apitokenDescRevoked := apitokenFields[9].Descriptor()
	// apitoken.DefaultRevoked holds the default value on creation for the revoked field.
	apitoken.DefaultRevoked = apitokenDescRevoked.Default.(bool)
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescStatus is the schema descriptor for status field.
	agentDescStatus := agentFields[5].Descriptor()
	// agent.DefaultStatus holds the default value on creation for the status field.
	agent.DefaultStatus = agentDescStatus.Default.(string)
	// agentDescSpecialties is the schema descriptor for specialties field.
	agentDescSpecialties := agentFields[6].Descriptor()
	// agent.DefaultSpecialties holds the default value on creation for the specialties field.
	agent.DefaultSpecialties = agentDescSpecialties.Default.(string)
	// agentDescConfig is the schema descriptor for config field.
	agentDescConfig := agentFields[7].Descriptor()
	// agent.DefaultConfig holds the default value on creation for the config field.
	agent.DefaultConfig = agentDescConfig.Default.(string)
	// agentDescRunnerType is the schema descriptor for runner_type field.
	agentDescRunnerType := agentFields[8].Descriptor()
	// agent.DefaultRunnerType holds the default value on creation for the runner_type field.
	agent.DefaultRunnerType = agentDescRunnerType.Default.(string)
	// agentDescRunnerConfig is the schema descriptor for runner_config field.
	agentDescRunnerConfig := agentFields[9].Descriptor()
	// agent.DefaultRunnerConfig holds the default value on creation for the runner_config field.
	agent.DefaultRunnerConfig = agentDescRunnerConfig.Default.(string)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[11].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	agentcallFields := schema.AgentCall{}.Fields()
	_ = agentcallFields
	// agentcallDescExitCode is the schema descriptor for exit_code field.
	agentcallDescExitCode := agentcallFields[7].Descriptor()
	// agentcall.DefaultExitCode holds the default value on creation for the exit_code field.
	agentcall.DefaultExitCode = agentcallDescExitCode.Default.(int)
	// agentcallDescDurationMs is the schema descriptor for duration_ms field.
	agentcallDescDurationMs := agentcallFields[10].Descriptor()
	// agentcall.DefaultDurationMs holds the default value on creation for the duration_ms field.
	agentcall.DefaultDurationMs = agentcallDescDurationMs.Default.(int64)
	// agentcallDescCreatedAt is the schema descriptor for created_at field.
	agentcallDescCreatedAt := agentcallFields[13].Descriptor()
	// agentcall.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentcall.DefaultCreatedAt = agentcallDescCreatedAt.Default.(func() time.Time)
	contextentryFields := schema.ContextEntry{}.Fields()
	_ = contextentryFields
	// contextentryDescUpdatedAt is the schema descriptor for updated_at field.
	contextentryDescUpdatedAt := contextentryFields[5].Descriptor()
	// contextentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contextentry.DefaultUpdatedAt = contextentryDescUpdatedAt.Default.(func() time.Time)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentFields[5].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescType is the schema descriptor for type field.
	documentDescType := documentFields[4].Descriptor()
	// document.DefaultType holds the default value on creation for the type field.
	document.DefaultType = documentDescType.Default.(string)
	// documentDescVersion is the schema descriptor for version field.
	documentDescVersion := documentFields[6].Descriptor()
	// document.DefaultVersion holds the default value on creation for the version field.
	document.DefaultVersion = documentDescVersion.Default.(int)
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[7].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescUpdatedAt is the schema descriptor for updated_at field.
	documentDescUpdatedAt := documentFields[8].Descriptor()
	// document.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	document.DefaultUpdatedAt = documentDescUpdatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescProjectID is the schema descriptor for project_id field.
	eventDescProjectID := eventFields[1].Descriptor()
	// event.DefaultProjectID holds the default value on creation for the project_id field.
	event.DefaultProjectID = eventDescProjectID.Default.(string)
	// eventDescTimestamp is the schema descriptor for timestamp field.
	eventDescTimestamp := eventFields[6].Descriptor()
	// event.DefaultTimestamp holds the default value on creation for the timestamp field.
	event.DefaultTimestamp = eventDescTimestamp.Default.(func() time.Time)
	// eventDescAttempt is the schema descriptor for attempt field.
	eventDescAttempt := eventFields[8].Descriptor()
	// event.DefaultAttempt holds the default value on creation for the attempt field.
	event.DefaultAttempt = eventDescAttempt.Default.(int)
	knowledgespaceFields := schema.KnowledgeSpace{}.Fields()
	_ = knowledgespaceFields
	// knowledgespaceDescProjectID is the schema descriptor for project_id field.
	knowledgespaceDescProjectID := knowledgespaceFields[2].Descriptor()
	// knowledgespace.DefaultProjectID holds the default value on creation for the project_id field.
	knowledgespace.DefaultProjectID = knowledgespaceDescProjectID.Default.(string)
	// knowledgespaceDescCreatedAt is the schema descriptor for created_at field.
	knowledgespaceDescCreatedAt := knowledgespaceFields[5].Descriptor()
	// knowledgespace.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledgespace.DefaultCreatedAt = knowledgespaceDescCreatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescType is the schema descriptor for type field.
	messageDescType := messageFields[4].Descriptor()
	// message.DefaultType holds the default value on creation for the type field.
	message.DefaultType = messageDescType.Default.(string)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[7].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[3].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[5].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCapabilities is the schema descriptor for capabilities field.
	roleDescCapabilities := roleFields[5].Descriptor()
	// role.DefaultCapabilities holds the default value on creation for the capabilities field.
	role.DefaultCapabilities = roleDescCapabilities.Default.(string)
	// roleDescLegacyPermissions is the schema descriptor for legacy_permissions field.
	roleDescLegacyPermissions := roleFields[6].Descriptor()
	// role.DefaultLegacyPermissions holds the default value on creation for the legacy_permissions field.
	role.DefaultLegacyPermissions = roleDescLegacyPermissions.Default.(string)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[7].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescProjectID is the schema descriptor for project_id field.
	taskDescProjectID := taskFields[1].Descriptor()
	// task.DefaultProjectID holds the default value on creation for the project_id field.
	task.DefaultProjectID = taskDescProjectID.Default.(string)
	// taskDescState is the schema descriptor for state field.
	taskDescState := taskFields[3].Descriptor()
	// task.DefaultState holds the default value on creation for the state field.
	task.DefaultState = taskDescState.Default.(string)
	// taskDescRetryCount is the schema descriptor for retry_count field.
	taskDescRetryCount := taskFields[4].Descriptor()
	// task.DefaultRetryCount holds the default value on creation for the retry_count field.
	task.DefaultRetryCount = taskDescRetryCount.Default.(int)
	// taskDescLoopIterationCount is the schema descriptor for loop_iteration_count field.
	taskDescLoopIterationCount := taskFields[5].Descriptor()
	// task.DefaultLoopIterationCount holds the default value on creation for the loop_iteration_count field.
	task.DefaultLoopIterationCount = taskDescLoopIterationCount.Default.(int)
	// taskDescTopoRank is the schema descriptor for topo_rank field.
	taskDescTopoRank := taskFields[8].Descriptor()
	// task.DefaultTopoRank holds the default value on creation for the topo_rank field.
	task.DefaultTopoRank = taskDescTopoRank.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[12].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[13].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// taskDescDepth is the schema descriptor for depth field.
	taskDescDepth := taskFields[18].Descriptor()
	// task.DefaultDepth holds the default value on creation for the depth field.
	task.DefaultDepth = taskDescDepth.Default.(int)
	// taskDescDecompositionStatus is the schema descriptor for decomposition_status field.
	taskDescDecompositionStatus := taskFields[19].Descriptor()
	// task.DefaultDecompositionStatus holds the default value on creation for the decomposition_status field.
	task.DefaultDecompositionStatus = taskDescDecompositionStatus.Default.(string)
	tasktemplateFields := schema.TaskTemplate{}.Fields()
	_ = tasktemplateFields
	// tasktemplateDescName is the schema descriptor for name field.
	tasktemplateDescName := tasktemplateFields[1].Descriptor()
	// tasktemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tasktemplate.NameValidator = func() func(string) error {
		validators := tasktemplateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tasktemplateDescProjectID is the schema descriptor for project_id field.
	tasktemplateDescProjectID := tasktemplateFields[3].Descriptor()
	// tasktemplate.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	tasktemplate.ProjectIDValidator = tasktemplateDescProjectID.Validators[0].(func(string) error)
	// tasktemplateDescOwnerAgent is the schema descriptor for owner_agent field.
	tasktemplateDescOwnerAgent := tasktemplateFields[4].Descriptor()
	// tasktemplate.DefaultOwnerAgent holds the default value on creation for the owner_agent field.
	tasktemplate.DefaultOwnerAgent = tasktemplateDescOwnerAgent.Default.(string)
	// tasktemplate.OwnerAgentValidator is a validator for the "owner_agent" field. It is called by the builders before save.
	tasktemplate.OwnerAgentValidator = tasktemplateDescOwnerAgent.Validators[0].(func(string) error)
	// tasktemplateDescTaskType is the schema descriptor for task_type field.
	tasktemplateDescTaskType := tasktemplateFields[5].Descriptor()
	// tasktemplate.DefaultTaskType holds the default value on creation for the task_type field.
	tasktemplate.DefaultTaskType = tasktemplateDescTaskType.Default.(string)
	// tasktemplate.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	tasktemplate.TaskTypeValidator = tasktemplateDescTaskType.Validators[0].(func(string) error)
	// tasktemplateDescPriority is the schema descriptor for priority field.
	tasktemplateDescPriority := tasktemplateFields[6].Descriptor()
	// tasktemplate.DefaultPriority holds the default value on creation for the priority field.
	tasktemplate.DefaultPriority = tasktemplateDescPriority.Default.(int)
	// tasktemplateDescWorkDir is the schema descriptor for work_dir field.
	tasktemplateDescWorkDir := tasktemplateFields[8].Descriptor()
	// tasktemplate.WorkDirValidator is a validator for the "work_dir" field. It is called by the builders before save.
	tasktemplate.WorkDirValidator = tasktemplateDescWorkDir.Validators[0].(func(string) error)
	// tasktemplateDescTimeoutSec is the schema descriptor for timeout_sec field.
	tasktemplateDescTimeoutSec := tasktemplateFields[9].Descriptor()
	// tasktemplate.DefaultTimeoutSec holds the default value on creation for the timeout_sec field.
	tasktemplate.DefaultTimeoutSec = tasktemplateDescTimeoutSec.Default.(int)
	// tasktemplateDescCreatedBy is the schema descriptor for created_by field.
	tasktemplateDescCreatedBy := tasktemplateFields[13].Descriptor()
	// tasktemplate.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	tasktemplate.CreatedByValidator = tasktemplateDescCreatedBy.Validators[0].(func(string) error)
	// tasktemplateDescCreatedAt is the schema descriptor for created_at field.
	tasktemplateDescCreatedAt := tasktemplateFields[14].Descriptor()
	// tasktemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	tasktemplate.DefaultCreatedAt = tasktemplateDescCreatedAt.Default.(func() time.Time)
	// tasktemplateDescUpdatedAt is the schema descriptor for updated_at field.
	tasktemplateDescUpdatedAt := tasktemplateFields[15].Descriptor()
	// tasktemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tasktemplate.DefaultUpdatedAt = tasktemplateDescUpdatedAt.Default.(func() time.Time)
	// tasktemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tasktemplate.UpdateDefaultUpdatedAt = tasktemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tasktemplateDescID is the schema descriptor for id field.
	tasktemplateDescID := tasktemplateFields[0].Descriptor()
	// tasktemplate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tasktemplate.IDValidator = tasktemplateDescID.Validators[0].(func(string) error)
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescCreatedAt is the schema descriptor for created_at field.
	teamDescCreatedAt := teamFields[6].Descriptor()
	// team.DefaultCreatedAt holds the default value on creation for the created_at field.
	team.DefaultCreatedAt = teamDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[5].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	waveFields := schema.Wave{}.Fields()
	_ = waveFields
	// waveDescProjectID is the schema descriptor for project_id field.
	waveDescProjectID := waveFields[0].Descriptor()
	// wave.DefaultProjectID holds the default value on creation for the project_id field.
	wave.DefaultProjectID = waveDescProjectID.Default.(string)
	// waveDescCreatedAt is the schema descriptor for created_at field.
	waveDescCreatedAt := waveFields[4].Descriptor()
	// wave.DefaultCreatedAt holds the default value on creation for the created_at field.
	wave.DefaultCreatedAt = waveDescCreatedAt.Default.(func() time.Time)
}
