// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/tasktemplate"
)

// TaskTemplateUpdate is the builder for updating TaskTemplate entities.
type TaskTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *TaskTemplateMutation
}

// Where appends a list predicates to the TaskTemplateUpdate builder.
func (_u *TaskTemplateUpdate) Where(ps ...predicate.TaskTemplate) *TaskTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TaskTemplateUpdate) SetName(v string) *TaskTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableName(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskTemplateUpdate) SetDescription(v string) *TaskTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableDescription(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskTemplateUpdate) ClearDescription() *TaskTemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskTemplateUpdate) SetProjectID(v string) *TaskTemplateUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableProjectID(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskTemplateUpdate) ClearProjectID() *TaskTemplateUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetOwnerAgent sets the "owner_agent" field.
func (_u *TaskTemplateUpdate) SetOwnerAgent(v string) *TaskTemplateUpdate {
	_u.mutation.SetOwnerAgent(v)
	return _u
}

// SetNillableOwnerAgent sets the "owner_agent" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableOwnerAgent(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetOwnerAgent(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskTemplateUpdate) SetTaskType(v string) *TaskTemplateUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableTaskType(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskTemplateUpdate) SetPriority(v int) *TaskTemplateUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillablePriority(v *int) *TaskTemplateUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaskTemplateUpdate) AddPriority(v int) *TaskTemplateUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetCommand sets the "command" field.
func (_u *TaskTemplateUpdate) SetCommand(v string) *TaskTemplateUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableCommand(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *TaskTemplateUpdate) ClearCommand() *TaskTemplateUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetWorkDir sets the "work_dir" field.
func (_u *TaskTemplateUpdate) SetWorkDir(v string) *TaskTemplateUpdate {
	_u.mutation.SetWorkDir(v)
	return _u
}

// SetNillableWorkDir sets the "work_dir" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableWorkDir(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetWorkDir(*v)
	}
	return _u
}

// ClearWorkDir clears the value of the "work_dir" field.
func (_u *TaskTemplateUpdate) ClearWorkDir() *TaskTemplateUpdate {
	_u.mutation.ClearWorkDir()
	return _u
}

// SetTimeoutSec sets the "timeout_sec" field.
func (_u *TaskTemplateUpdate) SetTimeoutSec(v int) *TaskTemplateUpdate {
	_u.mutation.ResetTimeoutSec()
	_u.mutation.SetTimeoutSec(v)
	return _u
}

// SetNillableTimeoutSec sets the "timeout_sec" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableTimeoutSec(v *int) *TaskTemplateUpdate {
	if v != nil {
		_u.SetTimeoutSec(*v)
	}
	return _u
}

// AddTimeoutSec adds value to the "timeout_sec" field.
func (_u *TaskTemplateUpdate) AddTimeoutSec(v int) *TaskTemplateUpdate {
	_u.mutation.AddTimeoutSec(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *TaskTemplateUpdate) SetTags(v []string) *TaskTemplateUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *TaskTemplateUpdate) AppendTags(v []string) *TaskTemplateUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *TaskTemplateUpdate) ClearTags() *TaskTemplateUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetInputs sets the "inputs" field.
func (_u *TaskTemplateUpdate) SetInputs(v []map[string]interface{}) *TaskTemplateUpdate {
	_u.mutation.SetInputs(v)
	return _u
}

// AppendInputs appends value to the "inputs" field.
func (_u *TaskTemplateUpdate) AppendInputs(v []map[string]interface{}) *TaskTemplateUpdate {
	_u.mutation.AppendInputs(v)
	return _u
}

// ClearInputs clears the value of the "inputs" field.
func (_u *TaskTemplateUpdate) ClearInputs() *TaskTemplateUpdate {
	_u.mutation.ClearInputs()
	return _u
}

// SetOutputs sets the "outputs" field.
func (_u *TaskTemplateUpdate) SetOutputs(v []map[string]interface{}) *TaskTemplateUpdate {
	_u.mutation.SetOutputs(v)
	return _u
}

// AppendOutputs appends value to the "outputs" field.
func (_u *TaskTemplateUpdate) AppendOutputs(v []map[string]interface{}) *TaskTemplateUpdate {
	_u.mutation.AppendOutputs(v)
	return _u
}

// ClearOutputs clears the value of the "outputs" field.
func (_u *TaskTemplateUpdate) ClearOutputs() *TaskTemplateUpdate {
	_u.mutation.ClearOutputs()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskTemplateUpdate) SetCreatedBy(v string) *TaskTemplateUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableCreatedBy(v *string) *TaskTemplateUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TaskTemplateUpdate) ClearCreatedBy() *TaskTemplateUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskTemplateUpdate) SetCreatedAt(v time.Time) *TaskTemplateUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskTemplateUpdate) SetNillableCreatedAt(v *time.Time) *TaskTemplateUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskTemplateUpdate) SetUpdatedAt(v time.Time) *TaskTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskTemplateMutation object of the builder.
func (_u *TaskTemplateUpdate) Mutation() *TaskTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tasktemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tasktemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := tasktemplate.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerAgent(); ok {
		if err := tasktemplate.OwnerAgentValidator(v); err != nil {
			return &ValidationError{Name: "owner_agent", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.owner_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := tasktemplate.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkDir(); ok {
		if err := tasktemplate.WorkDirValidator(v); err != nil {
			return &ValidationError{Name: "work_dir", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.work_dir": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := tasktemplate.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.created_by": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktemplate.Table, tasktemplate.Columns, sqlgraph.NewFieldSpec(tasktemplate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tasktemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tasktemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tasktemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(tasktemplate.FieldProjectID, field.TypeString, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(tasktemplate.FieldProjectID, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerAgent(); ok {
		_spec.SetField(tasktemplate.FieldOwnerAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(tasktemplate.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(tasktemplate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(tasktemplate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(tasktemplate.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(tasktemplate.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.WorkDir(); ok {
		_spec.SetField(tasktemplate.FieldWorkDir, field.TypeString, value)
	}
	if _u.mutation.WorkDirCleared() {
		_spec.ClearField(tasktemplate.FieldWorkDir, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutSec(); ok {
		_spec.SetField(tasktemplate.FieldTimeoutSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSec(); ok {
		_spec.AddField(tasktemplate.FieldTimeoutSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(tasktemplate.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(tasktemplate.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Inputs(); ok {
		_spec.SetField(tasktemplate.FieldInputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldInputs, value)
		})
	}
	if _u.mutation.InputsCleared() {
		_spec.ClearField(tasktemplate.FieldInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Outputs(); ok {
		_spec.SetField(tasktemplate.FieldOutputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldOutputs, value)
		})
	}
	if _u.mutation.OutputsCleared() {
		_spec.ClearField(tasktemplate.FieldOutputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tasktemplate.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tasktemplate.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tasktemplate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tasktemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskTemplateUpdateOne is the builder for updating a single TaskTemplate entity.
type TaskTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskTemplateMutation
}

// SetName sets the "name" field.
func (_u *TaskTemplateUpdateOne) SetName(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableName(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskTemplateUpdateOne) SetDescription(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableDescription(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskTemplateUpdateOne) ClearDescription() *TaskTemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskTemplateUpdateOne) SetProjectID(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableProjectID(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskTemplateUpdateOne) ClearProjectID() *TaskTemplateUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetOwnerAgent sets the "owner_agent" field.
func (_u *TaskTemplateUpdateOne) SetOwnerAgent(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetOwnerAgent(v)
	return _u
}

// SetNillableOwnerAgent sets the "owner_agent" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableOwnerAgent(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetOwnerAgent(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskTemplateUpdateOne) SetTaskType(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableTaskType(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskTemplateUpdateOne) SetPriority(v int) *TaskTemplateUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillablePriority(v *int) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaskTemplateUpdateOne) AddPriority(v int) *TaskTemplateUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetCommand sets the "command" field.
func (_u *TaskTemplateUpdateOne) SetCommand(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableCommand(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *TaskTemplateUpdateOne) ClearCommand() *TaskTemplateUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetWorkDir sets the "work_dir" field.
func (_u *TaskTemplateUpdateOne) SetWorkDir(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetWorkDir(v)
	return _u
}

// SetNillableWorkDir sets the "work_dir" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableWorkDir(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetWorkDir(*v)
	}
	return _u
}

// ClearWorkDir clears the value of the "work_dir" field.
func (_u *TaskTemplateUpdateOne) ClearWorkDir() *TaskTemplateUpdateOne {
	_u.mutation.ClearWorkDir()
	return _u
}

// SetTimeoutSec sets the "timeout_sec" field.
func (_u *TaskTemplateUpdateOne) SetTimeoutSec(v int) *TaskTemplateUpdateOne {
	_u.mutation.ResetTimeoutSec()
	_u.mutation.SetTimeoutSec(v)
	return _u
}

// SetNillableTimeoutSec sets the "timeout_sec" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableTimeoutSec(v *int) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetTimeoutSec(*v)
	}
	return _u
}

// AddTimeoutSec adds value to the "timeout_sec" field.
func (_u *TaskTemplateUpdateOne) AddTimeoutSec(v int) *TaskTemplateUpdateOne {
	_u.mutation.AddTimeoutSec(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *TaskTemplateUpdateOne) SetTags(v []string) *TaskTemplateUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *TaskTemplateUpdateOne) AppendTags(v []string) *TaskTemplateUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *TaskTemplateUpdateOne) ClearTags() *TaskTemplateUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetInputs sets the "inputs" field.
func (_u *TaskTemplateUpdateOne) SetInputs(v []map[string]interface{}) *TaskTemplateUpdateOne {
	_u.mutation.SetInputs(v)
	return _u
}

// AppendInputs appends value to the "inputs" field.
func (_u *TaskTemplateUpdateOne) AppendInputs(v []map[string]interface{}) *TaskTemplateUpdateOne {
	_u.mutation.AppendInputs(v)
	return _u
}

// ClearInputs clears the value of the "inputs" field.
func (_u *TaskTemplateUpdateOne) ClearInputs() *TaskTemplateUpdateOne {
	_u.mutation.ClearInputs()
	return _u
}

// SetOutputs sets the "outputs" field.
func (_u *TaskTemplateUpdateOne) SetOutputs(v []map[string]interface{}) *TaskTemplateUpdateOne {
	_u.mutation.SetOutputs(v)
	return _u
}

// AppendOutputs appends value to the "outputs" field.
func (_u *TaskTemplateUpdateOne) AppendOutputs(v []map[string]interface{}) *TaskTemplateUpdateOne {
	_u.mutation.AppendOutputs(v)
	return _u
}

// ClearOutputs clears the value of the "outputs" field.
func (_u *TaskTemplateUpdateOne) ClearOutputs() *TaskTemplateUpdateOne {
	_u.mutation.ClearOutputs()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskTemplateUpdateOne) SetCreatedBy(v string) *TaskTemplateUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableCreatedBy(v *string) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TaskTemplateUpdateOne) ClearCreatedBy() *TaskTemplateUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskTemplateUpdateOne) SetCreatedAt(v time.Time) *TaskTemplateUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskTemplateUpdateOne) SetNillableCreatedAt(v *time.Time) *TaskTemplateUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskTemplateUpdateOne) SetUpdatedAt(v time.Time) *TaskTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskTemplateMutation object of the builder.
func (_u *TaskTemplateUpdateOne) Mutation() *TaskTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskTemplateUpdate builder.
func (_u *TaskTemplateUpdateOne) Where(ps ...predicate.TaskTemplate) *TaskTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskTemplateUpdateOne) Select(field string, fields ...string) *TaskTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskTemplate entity.
func (_u *TaskTemplateUpdateOne) Save(ctx context.Context) (*TaskTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTemplateUpdateOne) SaveX(ctx context.Context) *TaskTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tasktemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tasktemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := tasktemplate.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerAgent(); ok {
		if err := tasktemplate.OwnerAgentValidator(v); err != nil {
			return &ValidationError{Name: "owner_agent", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.owner_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := tasktemplate.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkDir(); ok {
		if err := tasktemplate.WorkDirValidator(v); err != nil {
			return &ValidationError{Name: "work_dir", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.work_dir": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := tasktemplate.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "TaskTemplate.created_by": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskTemplateUpdateOne) sqlSave(ctx context.Context) (_node *TaskTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktemplate.Table, tasktemplate.Columns, sqlgraph.NewFieldSpec(tasktemplate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasktemplate.FieldID)
		for _, f := range fields {
			if !tasktemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tasktemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tasktemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tasktemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tasktemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(tasktemplate.FieldProjectID, field.TypeString, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(tasktemplate.FieldProjectID, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerAgent(); ok {
		_spec.SetField(tasktemplate.FieldOwnerAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(tasktemplate.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(tasktemplate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(tasktemplate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(tasktemplate.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(tasktemplate.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.WorkDir(); ok {
		_spec.SetField(tasktemplate.FieldWorkDir, field.TypeString, value)
	}
	if _u.mutation.WorkDirCleared() {
		_spec.ClearField(tasktemplate.FieldWorkDir, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutSec(); ok {
		_spec.SetField(tasktemplate.FieldTimeoutSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSec(); ok {
		_spec.AddField(tasktemplate.FieldTimeoutSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(tasktemplate.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(tasktemplate.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Inputs(); ok {
		_spec.SetField(tasktemplate.FieldInputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldInputs, value)
		})
	}
	if _u.mutation.InputsCleared() {
		_spec.ClearField(tasktemplate.FieldInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Outputs(); ok {
		_spec.SetField(tasktemplate.FieldOutputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tasktemplate.FieldOutputs, value)
		})
	}
	if _u.mutation.OutputsCleared() {
		_spec.ClearField(tasktemplate.FieldOutputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tasktemplate.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tasktemplate.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tasktemplate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tasktemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TaskTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
