// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/task"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *TaskCreate) SetProjectID(v string) *TaskCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableProjectID(v *string) *TaskCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetDispatchRef sets the "dispatch_ref" field.
func (_c *TaskCreate) SetDispatchRef(v string) *TaskCreate {
	_c.mutation.SetDispatchRef(v)
	return _c
}

// SetState sets the "state" field.
func (_c *TaskCreate) SetState(v string) *TaskCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *TaskCreate) SetNillableState(v *string) *TaskCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *TaskCreate) SetRetryCount(v int) *TaskCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *TaskCreate) SetNillableRetryCount(v *int) *TaskCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetLoopIterationCount sets the "loop_iteration_count" field.
func (_c *TaskCreate) SetLoopIterationCount(v int) *TaskCreate {
	_c.mutation.SetLoopIterationCount(v)
	return _c
}

// SetNillableLoopIterationCount sets the "loop_iteration_count" field if the given value is not nil.
func (_c *TaskCreate) SetNillableLoopIterationCount(v *int) *TaskCreate {
	if v != nil {
		_c.SetLoopIterationCount(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *TaskCreate) SetTransport(v string) *TaskCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetWave sets the "wave" field.
func (_c *TaskCreate) SetWave(v int) *TaskCreate {
	_c.mutation.SetWave(v)
	return _c
}

// SetTopoRank sets the "topo_rank" field.
func (_c *TaskCreate) SetTopoRank(v int) *TaskCreate {
	_c.mutation.SetTopoRank(v)
	return _c
}

// SetNillableTopoRank sets the "topo_rank" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTopoRank(v *int) *TaskCreate {
	if v != nil {
		_c.SetTopoRank(*v)
	}
	return _c
}

// SetWorkspacePath sets the "workspace_path" field.
func (_c *TaskCreate) SetWorkspacePath(v string) *TaskCreate {
	_c.mutation.SetWorkspacePath(v)
	return _c
}

// SetNillableWorkspacePath sets the "workspace_path" field if the given value is not nil.
func (_c *TaskCreate) SetNillableWorkspacePath(v *string) *TaskCreate {
	if v != nil {
		_c.SetWorkspacePath(*v)
	}
	return _c
}

// SetArtifactPath sets the "artifact_path" field.
func (_c *TaskCreate) SetArtifactPath(v string) *TaskCreate {
	_c.mutation.SetArtifactPath(v)
	return _c
}

// SetNillableArtifactPath sets the "artifact_path" field if the given value is not nil.
func (_c *TaskCreate) SetNillableArtifactPath(v *string) *TaskCreate {
	if v != nil {
		_c.SetArtifactPath(*v)
	}
	return _c
}

// SetLastErrorReason sets the "last_error_reason" field.
func (_c *TaskCreate) SetLastErrorReason(v string) *TaskCreate {
	_c.mutation.SetLastErrorReason(v)
	return _c
}

// SetNillableLastErrorReason sets the "last_error_reason" field if the given value is not nil.
func (_c *TaskCreate) SetNillableLastErrorReason(v *string) *TaskCreate {
	if v != nil {
		_c.SetLastErrorReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskCreate) SetUpdatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTerminalAt sets the "terminal_at" field.
func (_c *TaskCreate) SetTerminalAt(v time.Time) *TaskCreate {
	_c.mutation.SetTerminalAt(v)
	return _c
}

// SetNillableTerminalAt sets the "terminal_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTerminalAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetTerminalAt(*v)
	}
	return _c
}

// SetCardJSON sets the "card_json" field.
func (_c *TaskCreate) SetCardJSON(v string) *TaskCreate {
	_c.mutation.SetCardJSON(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v string) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := task.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := task.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := task.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.LoopIterationCount(); !ok {
		v := task.DefaultLoopIterationCount
		_c.mutation.SetLoopIterationCount(v)
	}
	if _, ok := _c.mutation.TopoRank(); !ok {
		v := task.DefaultTopoRank
		_c.mutation.SetTopoRank(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Task.project_id"`)}
	}
	if _, ok := _c.mutation.DispatchRef(); !ok {
		return &ValidationError{Name: "dispatch_ref", err: errors.New(`ent: missing required field "Task.dispatch_ref"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Task.state"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "Task.retry_count"`)}
	}
	if _, ok := _c.mutation.LoopIterationCount(); !ok {
		return &ValidationError{Name: "loop_iteration_count", err: errors.New(`ent: missing required field "Task.loop_iteration_count"`)}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "Task.transport"`)}
	}
	if _, ok := _c.mutation.Wave(); !ok {
		return &ValidationError{Name: "wave", err: errors.New(`ent: missing required field "Task.wave"`)}
	}
	if _, ok := _c.mutation.TopoRank(); !ok {
		return &ValidationError{Name: "topo_rank", err: errors.New(`ent: missing required field "Task.topo_rank"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	if _, ok := _c.mutation.CardJSON(); !ok {
		return &ValidationError{Name: "card_json", err: errors.New(`ent: missing required field "Task.card_json"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Task.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(task.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.DispatchRef(); ok {
		_spec.SetField(task.FieldDispatchRef, field.TypeString, value)
		_node.DispatchRef = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(task.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(task.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.LoopIterationCount(); ok {
		_spec.SetField(task.FieldLoopIterationCount, field.TypeInt, value)
		_node.LoopIterationCount = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(task.FieldTransport, field.TypeString, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.Wave(); ok {
		_spec.SetField(task.FieldWave, field.TypeInt, value)
		_node.Wave = value
	}
	if value, ok := _c.mutation.TopoRank(); ok {
		_spec.SetField(task.FieldTopoRank, field.TypeInt, value)
		_node.TopoRank = value
	}
	if value, ok := _c.mutation.WorkspacePath(); ok {
		_spec.SetField(task.FieldWorkspacePath, field.TypeString, value)
		_node.WorkspacePath = value
	}
	if value, ok := _c.mutation.ArtifactPath(); ok {
		_spec.SetField(task.FieldArtifactPath, field.TypeString, value)
		_node.ArtifactPath = value
	}
	if value, ok := _c.mutation.LastErrorReason(); ok {
		_spec.SetField(task.FieldLastErrorReason, field.TypeString, value)
		_node.LastErrorReason = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TerminalAt(); ok {
		_spec.SetField(task.FieldTerminalAt, field.TypeTime, value)
		_node.TerminalAt = value
	}
	if value, ok := _c.mutation.CardJSON(); ok {
		_spec.SetField(task.FieldCardJSON, field.TypeString, value)
		_node.CardJSON = value
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
