// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldID, id))
}

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSpaceID, v))
}

// FromAgentID applies equality check predicate on the "from_agent_id" field. It's identical to FromAgentIDEQ.
func FromAgentID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromAgentID, v))
}

// ToAgentID applies equality check predicate on the "to_agent_id" field. It's identical to ToAgentIDEQ.
func ToAgentID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldToAgentID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSpaceID, v))
}

// SpaceIDContains applies the Contains predicate on the "space_id" field.
func SpaceIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSpaceID, v))
}

// SpaceIDHasPrefix applies the HasPrefix predicate on the "space_id" field.
func SpaceIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSpaceID, v))
}

// SpaceIDHasSuffix applies the HasSuffix predicate on the "space_id" field.
func SpaceIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSpaceID, v))
}

// SpaceIDEqualFold applies the EqualFold predicate on the "space_id" field.
func SpaceIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSpaceID, v))
}

// SpaceIDContainsFold applies the ContainsFold predicate on the "space_id" field.
func SpaceIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSpaceID, v))
}

// FromAgentIDEQ applies the EQ predicate on the "from_agent_id" field.
func FromAgentIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromAgentID, v))
}

// FromAgentIDNEQ applies the NEQ predicate on the "from_agent_id" field.
func FromAgentIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldFromAgentID, v))
}

// FromAgentIDIn applies the In predicate on the "from_agent_id" field.
func FromAgentIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldFromAgentID, vs...))
}

// FromAgentIDNotIn applies the NotIn predicate on the "from_agent_id" field.
func FromAgentIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldFromAgentID, vs...))
}

// FromAgentIDGT applies the GT predicate on the "from_agent_id" field.
func FromAgentIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldFromAgentID, v))
}

// FromAgentIDGTE applies the GTE predicate on the "from_agent_id" field.
func FromAgentIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldFromAgentID, v))
}

// FromAgentIDLT applies the LT predicate on the "from_agent_id" field.
func FromAgentIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldFromAgentID, v))
}

// FromAgentIDLTE applies the LTE predicate on the "from_agent_id" field.
func FromAgentIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldFromAgentID, v))
}

// FromAgentIDContains applies the Contains predicate on the "from_agent_id" field.
func FromAgentIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldFromAgentID, v))
}

// FromAgentIDHasPrefix applies the HasPrefix predicate on the "from_agent_id" field.
func FromAgentIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldFromAgentID, v))
}

// FromAgentIDHasSuffix applies the HasSuffix predicate on the "from_agent_id" field.
func FromAgentIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldFromAgentID, v))
}

// FromAgentIDEqualFold applies the EqualFold predicate on the "from_agent_id" field.
func FromAgentIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldFromAgentID, v))
}

// FromAgentIDContainsFold applies the ContainsFold predicate on the "from_agent_id" field.
func FromAgentIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldFromAgentID, v))
}

// ToAgentIDEQ applies the EQ predicate on the "to_agent_id" field.
func ToAgentIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldToAgentID, v))
}

// ToAgentIDNEQ applies the NEQ predicate on the "to_agent_id" field.
func ToAgentIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldToAgentID, v))
}

// ToAgentIDIn applies the In predicate on the "to_agent_id" field.
func ToAgentIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldToAgentID, vs...))
}

// ToAgentIDNotIn applies the NotIn predicate on the "to_agent_id" field.
func ToAgentIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldToAgentID, vs...))
}

// ToAgentIDGT applies the GT predicate on the "to_agent_id" field.
func ToAgentIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldToAgentID, v))
}

// ToAgentIDGTE applies the GTE predicate on the "to_agent_id" field.
func ToAgentIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldToAgentID, v))
}

// ToAgentIDLT applies the LT predicate on the "to_agent_id" field.
func ToAgentIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldToAgentID, v))
}

// ToAgentIDLTE applies the LTE predicate on the "to_agent_id" field.
func ToAgentIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldToAgentID, v))
}

// ToAgentIDContains applies the Contains predicate on the "to_agent_id" field.
func ToAgentIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldToAgentID, v))
}

// ToAgentIDHasPrefix applies the HasPrefix predicate on the "to_agent_id" field.
func ToAgentIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldToAgentID, v))
}

// ToAgentIDHasSuffix applies the HasSuffix predicate on the "to_agent_id" field.
func ToAgentIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldToAgentID, v))
}

// ToAgentIDIsNil applies the IsNil predicate on the "to_agent_id" field.
func ToAgentIDIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldToAgentID))
}

// ToAgentIDNotNil applies the NotNil predicate on the "to_agent_id" field.
func ToAgentIDNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldToAgentID))
}

// ToAgentIDEqualFold applies the EqualFold predicate on the "to_agent_id" field.
func ToAgentIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldToAgentID, v))
}

// ToAgentIDContainsFold applies the ContainsFold predicate on the "to_agent_id" field.
func ToAgentIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldToAgentID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldContent, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReadAt, v))
}

// ReadAtIsNil applies the IsNil predicate on the "read_at" field.
func ReadAtIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldReadAt))
}

// ReadAtNotNil applies the NotNil predicate on the "read_at" field.
func ReadAtNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldReadAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
