// Code generated by ent, DO NOT EDIT.

package agentcall

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTaskID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldAgentID, v))
}

// RunnerType applies equality check predicate on the "runner_type" field. It's identical to RunnerTypeEQ.
func RunnerType(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldRunnerType, v))
}

// TaskType applies equality check predicate on the "task_type" field. It's identical to TaskTypeEQ.
func TaskType(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTaskType, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTraceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldStatus, v))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldExitCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldErrorMessage, v))
}

// OutputSummary applies equality check predicate on the "output_summary" field. It's identical to OutputSummaryEQ.
func OutputSummary(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldOutputSummary, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldDurationMs, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldTaskID, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldAgentID, v))
}

// RunnerTypeEQ applies the EQ predicate on the "runner_type" field.
func RunnerTypeEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldRunnerType, v))
}

// RunnerTypeNEQ applies the NEQ predicate on the "runner_type" field.
func RunnerTypeNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldRunnerType, v))
}

// RunnerTypeIn applies the In predicate on the "runner_type" field.
func RunnerTypeIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldRunnerType, vs...))
}

// RunnerTypeNotIn applies the NotIn predicate on the "runner_type" field.
func RunnerTypeNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldRunnerType, vs...))
}

// RunnerTypeGT applies the GT predicate on the "runner_type" field.
func RunnerTypeGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldRunnerType, v))
}

// RunnerTypeGTE applies the GTE predicate on the "runner_type" field.
func RunnerTypeGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldRunnerType, v))
}

// RunnerTypeLT applies the LT predicate on the "runner_type" field.
func RunnerTypeLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldRunnerType, v))
}

// RunnerTypeLTE applies the LTE predicate on the "runner_type" field.
func RunnerTypeLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldRunnerType, v))
}

// RunnerTypeContains applies the Contains predicate on the "runner_type" field.
func RunnerTypeContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldRunnerType, v))
}

// RunnerTypeHasPrefix applies the HasPrefix predicate on the "runner_type" field.
func RunnerTypeHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldRunnerType, v))
}

// RunnerTypeHasSuffix applies the HasSuffix predicate on the "runner_type" field.
func RunnerTypeHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldRunnerType, v))
}

// RunnerTypeEqualFold applies the EqualFold predicate on the "runner_type" field.
func RunnerTypeEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldRunnerType, v))
}

// RunnerTypeContainsFold applies the ContainsFold predicate on the "runner_type" field.
func RunnerTypeContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldRunnerType, v))
}

// TaskTypeEQ applies the EQ predicate on the "task_type" field.
func TaskTypeEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTaskType, v))
}

// TaskTypeNEQ applies the NEQ predicate on the "task_type" field.
func TaskTypeNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldTaskType, v))
}

// TaskTypeIn applies the In predicate on the "task_type" field.
func TaskTypeIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldTaskType, vs...))
}

// TaskTypeNotIn applies the NotIn predicate on the "task_type" field.
func TaskTypeNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldTaskType, vs...))
}

// TaskTypeGT applies the GT predicate on the "task_type" field.
func TaskTypeGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldTaskType, v))
}

// TaskTypeGTE applies the GTE predicate on the "task_type" field.
func TaskTypeGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldTaskType, v))
}

// TaskTypeLT applies the LT predicate on the "task_type" field.
func TaskTypeLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldTaskType, v))
}

// TaskTypeLTE applies the LTE predicate on the "task_type" field.
func TaskTypeLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldTaskType, v))
}

// TaskTypeContains applies the Contains predicate on the "task_type" field.
func TaskTypeContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldTaskType, v))
}

// TaskTypeHasPrefix applies the HasPrefix predicate on the "task_type" field.
func TaskTypeHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldTaskType, v))
}

// TaskTypeHasSuffix applies the HasSuffix predicate on the "task_type" field.
func TaskTypeHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldTaskType, v))
}

// TaskTypeEqualFold applies the EqualFold predicate on the "task_type" field.
func TaskTypeEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldTaskType, v))
}

// TaskTypeContainsFold applies the ContainsFold predicate on the "task_type" field.
func TaskTypeContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldTaskType, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDIsNil applies the IsNil predicate on the "trace_id" field.
func TraceIDIsNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIsNull(FieldTraceID))
}

// TraceIDNotNil applies the NotNil predicate on the "trace_id" field.
func TraceIDNotNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotNull(FieldTraceID))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldTraceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldStatus, v))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldExitCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldErrorMessage, v))
}

// OutputSummaryEQ applies the EQ predicate on the "output_summary" field.
func OutputSummaryEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldOutputSummary, v))
}

// OutputSummaryNEQ applies the NEQ predicate on the "output_summary" field.
func OutputSummaryNEQ(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldOutputSummary, v))
}

// OutputSummaryIn applies the In predicate on the "output_summary" field.
func OutputSummaryIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldOutputSummary, vs...))
}

// OutputSummaryNotIn applies the NotIn predicate on the "output_summary" field.
func OutputSummaryNotIn(vs ...string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldOutputSummary, vs...))
}

// OutputSummaryGT applies the GT predicate on the "output_summary" field.
func OutputSummaryGT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldOutputSummary, v))
}

// OutputSummaryGTE applies the GTE predicate on the "output_summary" field.
func OutputSummaryGTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldOutputSummary, v))
}

// OutputSummaryLT applies the LT predicate on the "output_summary" field.
func OutputSummaryLT(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldOutputSummary, v))
}

// OutputSummaryLTE applies the LTE predicate on the "output_summary" field.
func OutputSummaryLTE(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldOutputSummary, v))
}

// OutputSummaryContains applies the Contains predicate on the "output_summary" field.
func OutputSummaryContains(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContains(FieldOutputSummary, v))
}

// OutputSummaryHasPrefix applies the HasPrefix predicate on the "output_summary" field.
func OutputSummaryHasPrefix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasPrefix(FieldOutputSummary, v))
}

// OutputSummaryHasSuffix applies the HasSuffix predicate on the "output_summary" field.
func OutputSummaryHasSuffix(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldHasSuffix(FieldOutputSummary, v))
}

// OutputSummaryIsNil applies the IsNil predicate on the "output_summary" field.
func OutputSummaryIsNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIsNull(FieldOutputSummary))
}

// OutputSummaryNotNil applies the NotNil predicate on the "output_summary" field.
func OutputSummaryNotNil() predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotNull(FieldOutputSummary))
}

// OutputSummaryEqualFold applies the EqualFold predicate on the "output_summary" field.
func OutputSummaryEqualFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEqualFold(FieldOutputSummary, v))
}

// OutputSummaryContainsFold applies the ContainsFold predicate on the "output_summary" field.
func OutputSummaryContainsFold(v string) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldContainsFold(FieldOutputSummary, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldDurationMs, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldFinishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentCall {
	return predicate.AgentCall(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentCall) predicate.AgentCall {
	return predicate.AgentCall(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentCall) predicate.AgentCall {
	return predicate.AgentCall(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentCall) predicate.AgentCall {
	return predicate.AgentCall(sql.NotPredicates(p))
}
