// Code generated by ent, DO NOT EDIT.

package role

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mCP-DevOS/ai-orchestration-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldOrgID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldTeamID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldDescription, v))
}

// Capabilities applies equality check predicate on the "capabilities" field. It's identical to CapabilitiesEQ.
func Capabilities(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldCapabilities, v))
}

// LegacyPermissions applies equality check predicate on the "legacy_permissions" field. It's identical to LegacyPermissionsEQ.
func LegacyPermissions(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldLegacyPermissions, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldCreatedAt, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDIsNil applies the IsNil predicate on the "org_id" field.
func OrgIDIsNil() predicate.Role {
	return predicate.Role(sql.FieldIsNull(FieldOrgID))
}

// OrgIDNotNil applies the NotNil predicate on the "org_id" field.
func OrgIDNotNil() predicate.Role {
	return predicate.Role(sql.FieldNotNull(FieldOrgID))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldOrgID, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldTeamID, vs...))
}

// TeamIDGT applies the GT predicate on the "team_id" field.
func TeamIDGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldTeamID, v))
}

// TeamIDGTE applies the GTE predicate on the "team_id" field.
func TeamIDGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldTeamID, v))
}

// TeamIDLT applies the LT predicate on the "team_id" field.
func TeamIDLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldTeamID, v))
}

// TeamIDLTE applies the LTE predicate on the "team_id" field.
func TeamIDLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldTeamID, v))
}

// TeamIDContains applies the Contains predicate on the "team_id" field.
func TeamIDContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldTeamID, v))
}

// TeamIDHasPrefix applies the HasPrefix predicate on the "team_id" field.
func TeamIDHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldTeamID, v))
}

// TeamIDHasSuffix applies the HasSuffix predicate on the "team_id" field.
func TeamIDHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldTeamID, v))
}

// TeamIDIsNil applies the IsNil predicate on the "team_id" field.
func TeamIDIsNil() predicate.Role {
	return predicate.Role(sql.FieldIsNull(FieldTeamID))
}

// TeamIDNotNil applies the NotNil predicate on the "team_id" field.
func TeamIDNotNil() predicate.Role {
	return predicate.Role(sql.FieldNotNull(FieldTeamID))
}

// TeamIDEqualFold applies the EqualFold predicate on the "team_id" field.
func TeamIDEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldTeamID, v))
}

// TeamIDContainsFold applies the ContainsFold predicate on the "team_id" field.
func TeamIDContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldTeamID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Role {
	return predicate.Role(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Role {
	return predicate.Role(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldDescription, v))
}

// CapabilitiesEQ applies the EQ predicate on the "capabilities" field.
func CapabilitiesEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldCapabilities, v))
}

// CapabilitiesNEQ applies the NEQ predicate on the "capabilities" field.
func CapabilitiesNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldCapabilities, v))
}

// CapabilitiesIn applies the In predicate on the "capabilities" field.
func CapabilitiesIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldCapabilities, vs...))
}

// CapabilitiesNotIn applies the NotIn predicate on the "capabilities" field.
func CapabilitiesNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldCapabilities, vs...))
}

// CapabilitiesGT applies the GT predicate on the "capabilities" field.
func CapabilitiesGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldCapabilities, v))
}

// CapabilitiesGTE applies the GTE predicate on the "capabilities" field.
func CapabilitiesGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldCapabilities, v))
}

// CapabilitiesLT applies the LT predicate on the "capabilities" field.
func CapabilitiesLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldCapabilities, v))
}

// CapabilitiesLTE applies the LTE predicate on the "capabilities" field.
func CapabilitiesLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldCapabilities, v))
}

// CapabilitiesContains applies the Contains predicate on the "capabilities" field.
func CapabilitiesContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldCapabilities, v))
}

// CapabilitiesHasPrefix applies the HasPrefix predicate on the "capabilities" field.
func CapabilitiesHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldCapabilities, v))
}

// CapabilitiesHasSuffix applies the HasSuffix predicate on the "capabilities" field.
func CapabilitiesHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldCapabilities, v))
}

// CapabilitiesEqualFold applies the EqualFold predicate on the "capabilities" field.
func CapabilitiesEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldCapabilities, v))
}

// CapabilitiesContainsFold applies the ContainsFold predicate on the "capabilities" field.
func CapabilitiesContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldCapabilities, v))
}

// LegacyPermissionsEQ applies the EQ predicate on the "legacy_permissions" field.
func LegacyPermissionsEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldLegacyPermissions, v))
}

// LegacyPermissionsNEQ applies the NEQ predicate on the "legacy_permissions" field.
func LegacyPermissionsNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldLegacyPermissions, v))
}

// LegacyPermissionsIn applies the In predicate on the "legacy_permissions" field.
func LegacyPermissionsIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldLegacyPermissions, vs...))
}

// LegacyPermissionsNotIn applies the NotIn predicate on the "legacy_permissions" field.
func LegacyPermissionsNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldLegacyPermissions, vs...))
}

// LegacyPermissionsGT applies the GT predicate on the "legacy_permissions" field.
func LegacyPermissionsGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldLegacyPermissions, v))
}

// LegacyPermissionsGTE applies the GTE predicate on the "legacy_permissions" field.
func LegacyPermissionsGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldLegacyPermissions, v))
}

// LegacyPermissionsLT applies the LT predicate on the "legacy_permissions" field.
func LegacyPermissionsLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldLegacyPermissions, v))
}

// LegacyPermissionsLTE applies the LTE predicate on the "legacy_permissions" field.
func LegacyPermissionsLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldLegacyPermissions, v))
}

// LegacyPermissionsContains applies the Contains predicate on the "legacy_permissions" field.
func LegacyPermissionsContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldLegacyPermissions, v))
}

// LegacyPermissionsHasPrefix applies the HasPrefix predicate on the "legacy_permissions" field.
func LegacyPermissionsHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldLegacyPermissions, v))
}

// LegacyPermissionsHasSuffix applies the HasSuffix predicate on the "legacy_permissions" field.
func LegacyPermissionsHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldLegacyPermissions, v))
}

// LegacyPermissionsEqualFold applies the EqualFold predicate on the "legacy_permissions" field.
func LegacyPermissionsEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldLegacyPermissions, v))
}

// LegacyPermissionsContainsFold applies the ContainsFold predicate on the "legacy_permissions" field.
func LegacyPermissionsContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldLegacyPermissions, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UsersTable, UsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPermissions applies the HasEdge predicate on the "permissions" edge.
func HasPermissions() predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PermissionsTable, PermissionsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPermissionsWith applies the HasEdge predicate on the "permissions" edge with a given conditions (other predicates).
func HasPermissionsWith(preds ...predicate.Permission) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := newPermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Role) predicate.Role {
	return predicate.Role(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Role) predicate.Role {
	return predicate.Role(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Role) predicate.Role {
	return predicate.Role(sql.NotPredicates(p))
}
