// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Wave is the predicate function for wave builders.
type Wave func(*sql.Selector)
